### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by j2rong4cn** [Tornaco/Thanox#104]
系统：MIUI11 Android 10

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。

03-12 20:55:07.459  2851  2851 E EdXposed-Bridge: java.lang.ClassCastException: android.view.MotionEvent cannot be cast to android.view.KeyEvent
03-12 20:55:07.459  2851  2851 E EdXposed-Bridge: 	at github.tornaco.android.thanos.services.xposed.hooks.input.InputManagerInjectInputRegistry$1.afterHookedMethod(Unknown Source:22)
03-12 20:55:07.459  2851  2851 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
03-12 20:55:07.459  2851  2851 E EdXposed-Bridge: 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:388)
03-12 20:55:07.459  2851  2851 E EdXposed-Bridge: 	at SandHookerNew_1t62cb4026ao8bcvu8odth11tp.hook(Unknown Source:58)
03-12 20:55:07.459  2851  2851 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
03-12 20:55:07.459  2851  2851 E EdXposed-Bridge: 	at com.miui.home.recents.NavStubView.injectMotionEvent(NavStubView.java:878)
03-12 20:55:07.459  2851  2851 E EdXposed-Bridge: 	at com.miui.home.recents.NavStubView.access$2100(NavStubView.java:95)
03-12 20:55:07.459  2851  2851 E EdXposed-Bridge: 	at com.miui.home.recents.NavStubView$H.handleMessage(NavStubView.java:780)
03-12 20:55:07.459  2851  2851 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-12 20:55:07.459  2851  2851 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:227)
03-12 20:55:07.459  2851  2851 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:7545)
03-12 20:55:07.459  2851  2851 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
03-12 20:55:07.459  2851  2851 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
03-12 20:55:07.459  2851  2851 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

![Screenshot_2020-03-12-21-03-51-215_com termux](https://user-images.githubusercontent.com/36783515/76524416-fec5a000-64a4-11ea-879a-9d0626bfa8ee.jpg)

**Comment by j2rong4cn** [comment]
还有一个

03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: Adding TV input service @java.lang.Throwable
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at github.tornaco.android.thanos.services.xposed.hooks.ServiceManagerRegistry$1.beforeHookedMethod(Unknown Source:53)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:357)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at SandHookerNew_2nmeb0fr8t8stpg9ff8gpighe.hook(Unknown Source:62)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at github.tornaco.android.thanos.services.ThanosService.publishBinderService(Unknown Source:0)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at github.tornaco.android.thanos.services.ThanosService.publishBinderService(Unknown Source:1)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at github.tornaco.android.thanos.services.ThanosService.onStart(Unknown Source:97)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at github.tornaco.android.thanos.services.BootStrap.start(Unknown Source:12)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at github.tornaco.android.thanos.services.xposed.hooks.AMSBasicRegistry$1.beforeHookedMethod(Unknown Source:58)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:357)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at SandHookerNew_4d0upk0tf7q8f9b5ho838bonu.hook(Unknown Source:46)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at com.android.server.am.ActivityManagerService.access$1000(ActivityManagerService.java:411)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at com.android.server.am.ActivityManagerService$Lifecycle.onStart(ActivityManagerService.java:2267)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:129)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:116)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at com.android.server.am.ActivityManagerService$Lifecycle.startService(ActivityManagerService.java:2262)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:675)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:185)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:375)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at SandHookerNew_76sqduusglom4enahqif5d7ntb.hook(Unknown Source:46)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at com.android.server.SystemServer.run(SystemServer.java:523)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at com.android.server.SystemServer.main(SystemServer.java:362)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
03-12 21:06:40.059  1871  1871 I EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:931)

![Screenshot_2020-03-12-21-10-22-016_com termux](https://user-images.githubusercontent.com/36783515/76525083-2b2dec00-64a6-11ea-9fe0-fef7e0df0578.jpg)

**Comment by powerAn2020** [comment]
发现相同的问题，用的pro版本已加入测试版，但是依然报错，目前版本是4.1.7-row
```
[ 2023-03-29T15:44:52.563     1000:  2195:  2195 I/LSPosed-Bridge  ] Adding TV input service @java.lang.Throwable
	at github.tornaco.android.thanos.services.xposed.hooks.ServiceManagerRegistry$1.beforeHookedMethod(SourceFile:2)
	at FWeDpu.FzVaHfbpEWmTm.W.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.addService(Unknown Source:18)
	at github.tornaco.android.thanos.services.ThanoxServicePublisher.tryInstallReplaced(Unknown Source:5)
	at github.tornaco.android.thanos.services.ThanoxServicePublisher.publish(Unknown Source:17)
	at github.tornaco.android.thanos.services.ThanosService.publishBinderService(Unknown Source:9)
	at github.tornaco.android.thanos.services.ThanosService.systemReady(Unknown Source:14)
	at github.tornaco.android.thanos.services.BootStrap.ready(Unknown Source:6)
	at github.tornaco.android.thanos.services.xposed.hooks.AMSBasicRegistry$2.afterHookedMethod(Unknown Source:3)
	at FWeDpu.FzVaHfbpEWmTm.W.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.systemReady(Unknown Source:14)
	at com.android.server.SystemServer.startOtherServices(SystemServer.java:2963)
	at com.android.server.SystemServer.run(SystemServer.java:1000)
	at com.android.server.SystemServer.main(SystemServer.java:704)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
[ 2023-03-29T15:44:52.563     1000:  2195:  2195 I/LSPosed-Bridge  ] Thanos stub: github.tornaco.android.thanos.services.ThanosServiceStub@48b752a@thanox@tornaco:89c7072a-0bb8-4a86-8965-8cb5ed43d1fc
[ 2023-03-29T15:44:52.564     1000:  2195:  2195 I/LSPosed-Bridge  ] Adding TV input service @java.lang.Throwable
	at github.tornaco.android.thanos.services.xposed.hooks.ServiceManagerRegistry$1.beforeHookedMethod(SourceFile:2)
	at FWeDpu.FzVaHfbpEWmTm.W.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.addService(Unknown Source:25)
	at android.os.ServiceManager.addService(ServiceManager.java:195)
	at java.lang.reflect.Method.invoke(Native Method)
	at YZ.fzXcZvfVXnhlxcHkruo.c.Bqlc.HookBridge.invokeOriginalMethod(Native Method)
	at FWeDpu.FzVaHfbpEWmTm.W.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.addService(Unknown Source:18)
	at github.tornaco.android.thanos.services.ThanoxServicePublisher.tryInstallReplaced(Unknown Source:5)
	at github.tornaco.android.thanos.services.ThanoxServicePublisher.publish(Unknown Source:17)
	at github.tornaco.android.thanos.services.ThanosService.publishBinderService(Unknown Source:9)
	at github.tornaco.android.thanos.services.ThanosService.systemReady(Unknown Source:14)
	at github.tornaco.android.thanos.services.BootStrap.ready(Unknown Source:6)
	at github.tornaco.android.thanos.services.xposed.hooks.AMSBasicRegistry$2.afterHookedMethod(Unknown Source:3)
	at FWeDpu.FzVaHfbpEWmTm.W.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.systemReady(Unknown Source:14)
	at com.android.server.SystemServer.startOtherServices(SystemServer.java:2963)
	at com.android.server.SystemServer.run(SystemServer.java:1000)
	at com.android.server.SystemServer.main(SystemServer.java:704)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
```

**Comment by Tornaco** [comment]
@253551464 INFO级别的日志不是错误，仅为调试用。
