### ISSUE TITLE
启用Zygisk-LSPosed后灭霸app闪退

### ISSUE THREAD

**Issue by CECoffee** [Tornaco/Thanox#1078]
**现象描述**
启用Zygisk-LSPosed模块后app闪退，即便Thanox未激活。

**系统环境:**
 - Device: 小米15Pro
 - OS: HyperOS 2.0.17 (Android15)
 - Version: Thanox Pro 5.2.2
 - Root: Magisk Alpha(28001)
 - Zygisk实现: Zygisk Next 1.2.4(445-031a64c-release)
 - 相关模块: LSPosed内测版v1.9.2-it (7251)
 - Thanox补丁方式: 未启用

**Log:**
LSPosed日志文件
```
[ 2024-11-14T15:42:04.007     1000:  3738:  6297 I/LSPosed-Bridge  ] [ INFO] 11-14 15:42:04 (PmsHookTarget33) @shouldFilterApplication: query from com.greenpoint.android.mc10086.activity
[ 2024-11-14T15:42:04.007     1000:  3738:  6297 I/LSPosed-Bridge  ] [ INFO] 11-14 15:42:04 (PmsHookTarget33) @shouldFilterApplication: query from com.eg.android.AlipayGphone
[ 2024-11-14T15:42:04.007     1000:  3738:  6297 I/LSPosed-Bridge  ] [ INFO] 11-14 15:42:04 (PmsHookTarget33) @shouldFilterApplication: query from tv.danmaku.bili
[ 2024-11-14T15:42:04.007     1000:  3738:  6297 I/LSPosed-Bridge  ] [ INFO] 11-14 15:42:04 (PmsHookTarget33) @shouldFilterApplication: query from com.netease.cloudmusic
[ 2024-11-14T15:42:04.007     1000:  3738:  6297 I/LSPosed-Bridge  ] [ INFO] 11-14 15:42:04 (PmsHookTarget33) @shouldFilterApplication: query from io.github.vvb2060.mahoshojo
[ 2024-11-14T15:42:04.007     1000:  3738:  6297 I/LSPosed-Bridge  ] [ INFO] 11-14 15:42:04 (PmsHookTarget33) @shouldFilterApplication: query from com.taobao.taobao
[ 2024-11-14T15:42:04.007     1000:  3738:  6297 I/LSPosed-Bridge  ] [ INFO] 11-14 15:42:04 (PmsHookTarget33) @shouldFilterApplication: query from com.alibaba.android.rimet
[ 2024-11-14T15:42:04.007     1000:  3738:  6297 I/LSPosed-Bridge  ] [ INFO] 11-14 15:42:04 (PmsHookTarget33) @shouldFilterApplication: query from com.taobao.idlefish
[ 2024-11-14T15:42:04.008     1000:  3738:  6297 I/LSPosed-Bridge  ] [ INFO] 11-14 15:42:04 (PmsHookTarget33) @shouldFilterApplication: query from com.Shooter.ModernWarships
[ 2024-11-14T15:42:04.008     1000:  3738:  6297 I/LSPosed-Bridge  ] [ INFO] 11-14 15:42:04 (PmsHookTarget33) @shouldFilterApplication: query from com.chinamworld.main
[ 2024-11-14T15:42:04.008     1000:  3738:  6297 I/LSPosed-Bridge  ] [ INFO] 11-14 15:42:04 (PmsHookTarget33) @shouldFilterApplication: query from com.coolapk.market
[ 2024-11-14T15:42:04.008     1000:  3738:  6297 I/LSPosed-Bridge  ] [ INFO] 11-14 15:42:04 (PmsHookTarget33) @shouldFilterApplication: query from com.tencent.mobileqq
[ 2024-11-14T15:42:04.008     1000:  3738:  6297 I/LSPosed-Bridge  ] [ INFO] 11-14 15:42:04 (PmsHookTarget33) @shouldFilterApplication: query from com.google.android.gms
[ 2024-11-14T15:42:04.009     1000:  3738:  6297 I/LSPosed-Bridge  ] [ INFO] 11-14 15:42:04 (PmsHookTarget33) @shouldFilterApplication: query from com.chinamworld.bocmbci
[ 2024-11-14T15:42:04.009     1000:  3738:  6297 I/LSPosed-Bridge  ] [ INFO] 11-14 15:42:04 (PmsHookTarget33) @shouldFilterApplication: query from com.tencent.mm
[ 2024-11-14T15:42:04.010     1000:  3738:  6297 I/LSPosed-Bridge  ] [ INFO] 11-14 15:42:04 (PmsHookTarget33) @shouldFilterApplication: query from com.MobileTicket
[ 2024-11-14T15:42:04.010     1000:  3738:  6297 I/LSPosed-Bridge  ] [ INFO] 11-14 15:42:04 (PmsHookTarget33) @shouldFilterApplication: query from com.dianping.v1
[ 2024-11-14T15:42:04.010     1000:  3738:  6297 I/LSPosed-Bridge  ] [ INFO] 11-14 15:42:04 (PmsHookTarget33) @shouldFilterApplication: query from com.sankuai.meituan
[ 2024-11-14T15:42:04.010     1000:  3738:  6297 I/LSPosed-Bridge  ] [ INFO] 11-14 15:42:04 (PmsHookTarget33) @shouldFilterApplication: query from com.tmri.app.main
[ 2024-11-14T15:42:04.010     1000:  3738:  6297 I/LSPosed-Bridge  ] [ INFO] 11-14 15:42:04 (PmsHookTarget33) @shouldFilterApplication: query from icu.nullptr.applistdetector
[ 2024-11-14T15:42:04.037     1000:  3738:  5443 I/LSPosed-Bridge  ] [ INFO] 11-14 15:42:04 (PmsHookTarget33) @shouldFilterApplication: query from com.google.android.gms
[ 2024-11-14T15:42:04.179    10315:  9967:  9967 E/AndroidRuntime  ] FATAL EXCEPTION: main
Process: github.tornaco.android.thanos.pro, PID: 9967
java.lang.SecurityException: Unknown calling package name 'github.tornaco.android.thanos.pro'.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3256)
	at android.os.Parcel.createException(Parcel.java:3240)
	at android.os.Parcel.readException(Parcel.java:3223)
	at android.os.Parcel.readException(Parcel.java:3165)
	at ggz.hqxg.ghni.vya.B(SourceFile:32)
	at ggz.hqxg.ghni.yua.p(SourceFile:113)
	at ggz.hqxg.ghni.m4b.b(SourceFile:7)
	at ggz.hqxg.ghni.c0b.handleMessage(SourceFile:364)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at ggz.hqxg.ghni.z23.dispatchMessage(SourceFile:6)
	at android.os.Looper.loopOnce(Looper.java:249)
	at android.os.Looper.loop(Looper.java:337)
	at android.app.ActivityThread.main(ActivityThread.java:9572)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)`
```

**Comment by CECoffee** [comment]
发现该问题为隐藏应用列表对gms生效，导致谷歌无法验证购买ThanoxPro所致。将thanox移出gms黑名单即可。国内版本理论上不存在此问题
