### ISSUE TITLE
MIUI12乖巧(不关服务只休眠)等功能失效

### ISSUE THREAD

**Issue by Sizumei** [Tornaco/Thanox#135]
**Describe the bug（现象描述）**
1.miui12乖巧休眠无效果，日志显示无权限设置idle状态
2.禁用启用应用组件时也报权限异常
**Version（发现问题的版本）:**
miui12 android10
** Logs**（日志文件）
05-04 13:37:24.105  2077  2249 E EdXposed-Bridge: java.lang.SecurityException: No permission to change app idle state: uid 1000 does not have android.permission.CHANGE_APP_IDLE_STATE.
05-04 13:37:24.105  2077  2249 E EdXposed-Bridge: 	at android.app.ContextImpl.enforce(ContextImpl.java:1906)
05-04 13:37:24.105  2077  2249 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
05-04 13:37:24.105  2077  2249 E EdXposed-Bridge: 	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:185)
05-04 13:37:24.105  2077  2249 E EdXposed-Bridge: 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:379)
05-04 13:37:24.105  2077  2249 E EdXposed-Bridge: 	at SandHookerNew_2c1n20mle22b90v5l1tl3tj3c4.hook(Unknown Source:77)
05-04 13:37:24.105  2077  2249 E EdXposed-Bridge: 	at android.app.ContextImpl.enforceCallingPermission(ContextImpl.java:1924)
05-04 13:37:24.105  2077  2249 E EdXposed-Bridge: 	at com.android.server.usage.UsageStatsService$BinderService.setAppInactive(UsageStatsService.java:1205)
05-04 13:37:24.105  2077  2249 E EdXposed-Bridge: 	at github.tornaco.android.thanos.services.app.ActivityManagerService.e(Unknown Source:20)
05-04 13:37:24.105  2077  2249 E EdXposed-Bridge: 	at github.tornaco.android.thanos.services.app.q0.run(Unknown Source:4)
05-04 13:37:24.105  2077  2249 E EdXposed-Bridge: 	at c.a.u.e.a.e.b(Unknown Source:9)
05-04 13:37:24.105  2077  2249 E EdXposed-Bridge: 	at c.a.b.a(Unknown Source:5)
05-04 13:37:24.105  2077  2249 E EdXposed-Bridge: 	at c.a.u.e.a.h$a.run(Unknown Source:4)
05-04 13:37:24.105  2077  2249 E EdXposed-Bridge: 	at j.a.b.d$b.run(Unknown Source:2)
05-04 13:37:24.105  2077  2249 E EdXposed-Bridge: 	at android.os.Handler.handleCallback(Handler.java:914)
05-04 13:37:24.105  2077  2249 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-04 13:37:24.105  2077  2249 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:228)
05-04 13:37:24.105  2077  2249 E EdXposed-Bridge: 	at android.os.HandlerThread.run(HandlerThread.java:67)

05-04 13:39:14.856  2077  2163 E EdXposed-Bridge: java.lang.SecurityException: setEnabled: Neither user 10077 nor current process has android.permission.CHANGE_OVERLAY_PACKAGES.
05-04 13:39:14.856  2077  2163 E EdXposed-Bridge: 	at android.app.ContextImpl.enforce(ContextImpl.java:1906)
05-04 13:39:14.856  2077  2163 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
05-04 13:39:14.856  2077  2163 E EdXposed-Bridge: 	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:185)
05-04 13:39:14.856  2077  2163 E EdXposed-Bridge: 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:379)
05-04 13:39:14.856  2077  2163 E EdXposed-Bridge: 	at SandHookerNew_2c1n20mle22b90v5l1tl3tj3c4.hook(Unknown Source:77)
05-04 13:39:14.856  2077  2163 E EdXposed-Bridge: 	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1934)
05-04 13:39:14.856  2077  2163 E EdXposed-Bridge: 	at com.android.server.om.OverlayManagerService$1.enforceChangeOverlayPackagesPermission(OverlayManagerService.java:856)
05-04 13:39:14.856  2077  2163 E EdXposed-Bridge: 	at com.android.server.om.OverlayManagerService$1.setEnabled(OverlayManagerService.java:588)
05-04 13:39:14.856  2077  2163 E EdXposed-Bridge: 	at android.content.om.IOverlayManager$Stub.onTransact(IOverlayManager.java:315)
05-04 13:39:14.856  2077  2163 E EdXposed-Bridge: 	at android.os.Binder.execTransactInternal(Binder.java:1021)
05-04 13:39:14.856  2077  2163 E EdXposed-Bridge: 	at android.os.Binder.execTransact(Binder.java:994)

**Comment by Tornaco** [comment]
@Sizumei  激活后“重启”设备了吗？不是软重启。

**Comment by Sizumei** [comment]
重启了，日志只复制了两个，core日志太长，复制不过来
2020－05－06：
1588746747502|W|ThanoxApp|CpuUsagePercent[s[999C[999B[6n[u[H[J[?25l[H[J[s[999C[999B[6n[uTasks: 1 total,   1 running,   0 sleeping,   0 stopped,   0 zombie  Mem:      5.4G total,      5.4G used,       67M free,      109M buffers Swap:      2.5G total,       40M used,      2.4G free,      1.5G cached800%cpu   0%user   0%nice   0%sys 800%idle   0%iow   0%irq   0%sirq   0%host[7m  PID USER         PR  NI VIRT  RES  SHR S[%CPU] %MEM     TIME+ ARGS            [0m[1m 6500 u0_a233      10 -10  35M 2.6M 2.0M R  0.0   0.0   0:00.01 top -n 1[m[?25h[0m[1000;1H[K[?25h[?25h[0m[1000;1H[K
1588746747666|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1588746747667|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1588746747667|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1588746747668|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1588746747753|V|ThanoxApp|isPaid? true
1588746747857|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1588746747881|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1588746747922|D|ThanoxApp|onAttach
1588746747922|D|ThanoxApp|onCreate
1588746747922|D|ThanoxApp|onAttach
1588746747922|D|ThanoxApp|onCreate
1588746747924|D|ThanoxApp|onActivityCreated
1588746747977|D|ThanoxApp|onActivityCreated

thanox-init：
ThanosS: Bring up with thanos: github.tornaco.android.thanos.services.ThanosService@3dab020, sdk: 29
ThanosS: hookGetStringForUser...
ThanosS: hookGetStringForUser OK:[de.robv.android.xposed.XC_MethodHook$Unhook@79393b2]
ThanosS: TelephonyManagerRegister hookTelephonyManagerGetDeviceId...
ThanosS: TelephonyManagerRegister hookTelephonyManagerGetDeviceId OK:[de.robv.android.xposed.XC_MethodHook$Unhook@e0be80, de.robv.android.xposed.XC_MethodHook$Unhook@e824f03]
ThanosS: TelephonyManagerRegister hookTelephonyManagerGetLine1Number...
ThanosS: TelephonyManagerRegister hookTelephonyManagerGetLine1Number OK:[de.robv.android.xposed.XC_MethodHook$Unhook@bc4cb9, de.robv.android.xposed.XC_MethodHook$Unhook@fa338fe]
ThanosS: TelephonyManagerRegister hookTelephonyManagerGetSimSerial...
ThanosS: TelephonyManagerRegister hookTelephonyManagerGetSimSerial OK:[de.robv.android.xposed.XC_MethodHook$Unhook@650d85f, de.robv.android.xposed.XC_MethodHook$Unhook@ad342ac]
ThanosS: TelephonyManagerRegister hookTelephonyManagerGetImei...
ThanosS: getImeiWithSlotIndexMethod method: public java.lang.String android.telephony.TelephonyManager.getImei(int)
ThanosS: TelephonyManagerRegister hookTelephonyManagerGetImei OK:de.robv.android.xposed.XC_MethodHook$Unhook@74bfb75
ThanosS: TelephonyManagerRegister hookTelephonyManagerGetMeid...
ThanosS: getMeidWithSlotIndexMethod method: public java.lang.String android.telephony.TelephonyManager.getMeid(int)
ThanosS: TelephonyManagerRegister hookTelephonyManagerGetMeid OK:de.robv.android.xposed.XC_MethodHook$Unhook@375e70a
ThanosS: hookInjectInputEvent...
ThanosS: hookInjectInputEvent OK:[de.robv.android.xposed.XC_MethodHook$Unhook@1549b7b]
ThanosS: hookOnDebugDraw...
ThanosS: hookOnDebugDraw OK:[de.robv.android.xposed.XC_MethodHook$Unhook@5077457]
ThanosS: ContextImplSubModule hookEnforce...
ThanosS: ContextImplSubModule hookEnforce OK:[de.robv.android.xposed.XC_MethodHook$Unhook@cf5242d]
ThanosS: hookAddService...
ThanosS: hookAddService...[de.robv.android.xposed.XC_MethodHook$Unhook@58dddae, de.robv.android.xposed.XC_MethodHook$Unhook@eacd629, de.robv.android.xposed.XC_MethodHook$Unhook@986974f]
ThanosS: hookNotifyWakeLockAcquired, unhooks [de.robv.android.xposed.XC_MethodHook$Unhook@5e4f2d3]
ThanosS: notifyWakeLockReleasedLocked, unhooks [de.robv.android.xposed.XC_MethodHook$Unhook@6a9de10]
ThanosS: hookGetInstalledPkgs...
ThanosS: hookGetInstalledPkgs OK:[de.robv.android.xposed.XC_MethodHook$Unhook@53dcb0e]
ThanosS: hookGetInstalledApps...
ThanosS: hookGetInstalledApps OK:[de.robv.android.xposed.XC_MethodHook$Unhook@a01e92f]
ThanosS: hookQueryIntentActivities...
ThanosS: hookQueryIntentActivities OK:[de.robv.android.xposed.XC_MethodHook$Unhook@136cb3c]
ThanosS: hook PowerManagerService$LocalService...
ThanosS: ANDROID_UTIL_LOG_PRINTER
ThanosS: 
**** CLAZZ DUMPER START DUMP OF class com.android.server.power.PowerManagerService$LocalService ***
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public void com.android.server.power.PowerManagerService$LocalService.addVisibleWindowUids(int) 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public void com.android.server.power.PowerManagerService$LocalService.clearVisibleWindowUids() 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public void com.android.server.power.PowerManagerService$LocalService.finishUidChanges() 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public android.os.PowerManager$WakeData com.android.server.power.PowerManagerService$LocalService.getLastWakeup() 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public android.os.PowerSaveState com.android.server.power.PowerManagerService$LocalService.getLowPowerState(int) 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public void com.android.server.power.PowerManagerService$LocalService.powerHint(int,int) 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public void com.android.server.power.PowerManagerService$LocalService.registerLowPowerModeObserver(android.os.PowerManagerInternal$LowPowerModeListener) 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public boolean com.android.server.power.PowerManagerService$LocalService.setDeviceIdleMode(boolean) 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public void com.android.server.power.PowerManagerService$LocalService.setDeviceIdleTempWhitelist(int[]) 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public void com.android.server.power.PowerManagerService$LocalService.setDeviceIdleWhitelist(int[]) 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public void com.android.server.power.PowerManagerService$LocalService.setDozeOverrideFromDreamManager(int,int) 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public void com.android.server.power.PowerManagerService$LocalService.setDrawWakeLockOverrideFromSidekick(boolean) 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public boolean com.android.server.power.PowerManagerService$LocalService.setLightDeviceIdleMode(boolean) 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public void com.android.server.power.PowerManagerService$LocalService.setMaximumScreenOffTimeoutFromDeviceAdmin(int,long) 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public void com.android.server.power.PowerManagerService$LocalService.setScreenBrightnessOverrideFromWindowManager(int) 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public void com.android.server.power.PowerManagerService$LocalService.setUserActivityTimeoutOverrideFromWindowManager(long) 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public void com.android.server.power.PowerManagerService$LocalService.setUserInactiveOverrideFromWindowManager() 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public void com.android.server.power.PowerManagerService$LocalService.startUidChanges() 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public void com.android.server.power.PowerManagerService$LocalService.summonSandman() 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public void com.android.server.power.PowerManagerService$LocalService.uidActive(int) 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public void com.android.server.power.PowerManagerService$LocalService.uidGone(int) 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public void com.android.server.power.PowerManagerService$LocalService.uidIdle(int) 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public void com.android.server.power.PowerManagerService$LocalService.updateUidProcState(int,int) 
ThanosS: METHOD OF CLASS class com.android.server.power.PowerManagerService$LocalService: public boolean com.android.server.power.PowerManagerService$LocalService.wasDeviceIdleFor(long) 
ThanosS: FIELD OF CLASS class com.android.server.power.PowerManagerService$LocalService: final com.android.server.power.PowerManagerService com.android.server.power.PowerManagerService$LocalService.this$0
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public static boolean android.os.PowerManagerInternal.isInteractive(int) 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public static int android.os.PowerManagerInternal.wakefulnessToProtoEnum(int) 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public static java.lang.String android.os.PowerManagerInternal.wakefulnessToString(int) 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract void android.os.PowerManagerInternal.addVisibleWindowUids(int) 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract void android.os.PowerManagerInternal.clearVisibleWindowUids() 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract void android.os.PowerManagerInternal.finishUidChanges() 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract android.os.PowerManager$WakeData android.os.PowerManagerInternal.getLastWakeup() 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract android.os.PowerSaveState android.os.PowerManagerInternal.getLowPowerState(int) 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract void android.os.PowerManagerInternal.powerHint(int,int) 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public void android.os.PowerManagerInternal.registerLowPowerModeObserver(int,java.util.function.Consumer) 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract void android.os.PowerManagerInternal.registerLowPowerModeObserver(android.os.PowerManagerInternal$LowPowerModeListener) 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract boolean android.os.PowerManagerInternal.setDeviceIdleMode(boolean) 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract void android.os.PowerManagerInternal.setDeviceIdleTempWhitelist(int[]) 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract void android.os.PowerManagerInternal.setDeviceIdleWhitelist(int[]) 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract void android.os.PowerManagerInternal.setDozeOverrideFromDreamManager(int,int) 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract void android.os.PowerManagerInternal.setDrawWakeLockOverrideFromSidekick(boolean) 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract boolean android.os.PowerManagerInternal.setLightDeviceIdleMode(boolean) 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract void android.os.PowerManagerInternal.setMaximumScreenOffTimeoutFromDeviceAdmin(int,long) 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract void android.os.PowerManagerInternal.setScreenBrightnessOverrideFromWindowManager(int) 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract void android.os.PowerManagerInternal.setUserActivityTimeoutOverrideFromWindowManager(long) 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract void android.os.PowerManagerInternal.setUserInactiveOverrideFromWindowManager() 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract void android.os.PowerManagerInternal.startUidChanges() 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract void android.os.PowerManagerInternal.summonSandman() 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract void android.os.PowerManagerInternal.uidActive(int) 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract void android.os.PowerManagerInternal.uidGone(int) 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract void android.os.PowerManagerInternal.uidIdle(int) 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract void android.os.PowerManagerInternal.updateUidProcState(int,int) 
ThanosS: METHOD OF CLASS class android.os.PowerManagerInternal: public abstract boolean android.os.PowerManagerInternal.wasDeviceIdleFor(long) 
ThanosS: FIELD OF CLASS class android.os.PowerManagerInternal: final com.android.server.power.PowerManagerService com.android.server.power.PowerManagerService$LocalService.this$0
ThanosS: METHOD OF CLASS class java.lang.Object: static int java.lang.Object.identityHashCode(java.lang.Object) 
ThanosS: METHOD OF CLASS class java.lang.Object: private static native int java.lang.Object.identityHashCodeNative(java.lang.Object) 
ThanosS: METHOD OF CLASS class java.lang.Object: private native java.lang.Object java.lang.Object.internalClone() 
ThanosS: METHOD OF CLASS class java.lang.Object: protected java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException 
ThanosS: METHOD OF CLASS class java.lang.Object: public boolean java.lang.Object.equals(java.lang.Object) 
ThanosS: METHOD OF CLASS class java.lang.Object: protected void java.lang.Object.finalize() throws java.lang.Throwable 
ThanosS: METHOD OF CLASS class java.lang.Object: public final java.lang.Class java.lang.Object.getClass() 
ThanosS: METHOD OF CLASS class java.lang.Object: public int java.lang.Object.hashCode() 
ThanosS: METHOD OF CLASS class java.lang.Object: public final native void java.lang.Object.notify() 
ThanosS: METHOD OF CLASS class java.lang.Object: public final native void java.lang.Object.notifyAll() 
ThanosS: METHOD OF CLASS class java.lang.Object: public java.lang.String java.lang.Object.toString() 
ThanosS: METHOD OF CLASS class java.lang.Object: public final void java.lang.Object.wait() throws java.lang.InterruptedException 
ThanosS: METHOD OF CLASS class java.lang.Object: public final void java.lang.Object.wait(long) throws java.lang.InterruptedException 
ThanosS: METHOD OF CLASS class java.lang.Object: public final native void java.lang.Object.wait(long,int) throws java.lang.InterruptedException 
ThanosS: FIELD OF CLASS class java.lang.Object: final com.android.server.power.PowerManagerService com.android.server.power.PowerManagerService$LocalService.this$0
ThanosS: **** CLAZZ DUMPER END DUMP OF class com.android.server.power.PowerManagerService$LocalService ***

ThanosS: ANDROID_UTIL_LOG_PRINTER
ThanosS: hook PowerManagerService$LocalService OK:[de.robv.android.xposed.XC_MethodHook$Unhook@d8f8a1a]
ThanosS: hookAMSStart, unhooks [de.robv.android.xposed.XC_MethodHook$Unhook@c4de94b]
ThanosS: hookAMSSystemReady, unhooks [de.robv.android.xposed.XC_MethodHook$Unhook@5435f28]
ThanosS: hookAMSShutdown, unhooks [de.robv.android.xposed.XC_MethodHook$Unhook@59de441]
ThanosS: hookBroadcastIntent, unhooks [de.robv.android.xposed.XC_MethodHook$Unhook@b0c2de6]
ThanosS: handleApplicationCrashInner, unhooks [de.robv.android.xposed.XC_MethodHook$Unhook@fcf27]
ThanosS: hookNativeInjectInputEvent...
ThanosS: hookNativeInjectInputEvent OK:[de.robv.android.xposed.XC_MethodHook$Unhook@70345d4]
ThanosS: hookInterceptKeyBeforeQueueing...
ThanosS: hookInterceptKeyBeforeQueueing OK:[de.robv.android.xposed.XC_MethodHook$Unhook@1a3837d]
ThanosS: hookNMSStart, unhooks [de.robv.android.xposed.XC_MethodHook$Unhook@c2036c3]
ThanosS: hookReportActivityVisible...
ThanosS: hookReportActivityVisible OK:[]
ThanosS: hookStartLaunchTickingLocked...
ThanosS: hookStartLaunchTickingLocked OK:[de.robv.android.xposed.XC_MethodHook$Unhook@b69da79]
ThanosS: hookResumeTopActivityInnerLocked, unhooks [de.robv.android.xposed.XC_MethodHook$Unhook@2457c1f]
ThanosS: hookRealStartActivityLocked...
ThanosS: hookRealStartActivityLocked OK:[de.robv.android.xposed.XC_MethodHook$Unhook@8a4a535]
ThanosS: hookCheckStartAnyActivityPermission...
ThanosS: hookCheckStartAnyActivityPermission OK:[de.robv.android.xposed.XC_MethodHook$Unhook@46eadca]
ThanosS: hookStartActivityMayWait...
ThanosS: startActivityMayWait method:private int com.android.server.wm.ActivityStarter.startActivityMayWait(android.app.IApplicationThread,int,java.lang.String,int,int,android.content.Intent,java.lang.String,android.service.voice.IVoiceInteractionSession,com.android.internal.app.IVoiceInteractor,android.os.IBinder,java.lang.String,int,int,android.app.ProfilerInfo,android.app.WaitResult,android.content.res.Configuration,com.android.server.wm.SafeActivityOptions,boolean,int,com.android.server.wm.TaskRecord,java.lang.String,boolean,com.android.server.am.PendingIntentRecord,boolean)
ThanosS: intentIndex index:5
ThanosS: activityOptsIndex index:-1
ThanosS: hookStartActivityMayWait OK: de.robv.android.xposed.XC_MethodHook$Unhook@7a0e258
ThanosS: LauncherAppServiceSubModule hookStartShortcut...
ThanosS: startShortcut method: public boolean com.android.server.pm.LauncherAppsService$LauncherAppsImpl.startShortcut(java.lang.String,java.lang.String,java.lang.String,android.graphics.Rect,android.os.Bundle,int)
ThanosS: LauncherAppServiceSubModule hookStartShortcut OK:de.robv.android.xposed.XC_MethodHook$Unhook@8b1dc96
ThanosS: LauncherAppServiceSubModule hookVerifyCallingPackage...
ThanosS: verifyCallingPackage method: void com.android.server.pm.LauncherAppsService$LauncherAppsImpl.verifyCallingPackage(java.lang.String)
ThanosS: LauncherAppServiceSubModule hookVerifyCallingPackage OK:de.robv.android.xposed.XC_MethodHook$Unhook@6f4d017
ThanosS: hookTaskMover...
ThanosS: hookTaskMover OK:de.robv.android.xposed.XC_MethodHook$Unhook@66dcc04
ThanosS: hookIntentFireWall...
ThanosS: hookIntentFireWall checkService OK:[de.robv.android.xposed.XC_MethodHook$Unhook@6272c22]
ThanosS: hookIntentFireWall checkBroadcast OK:[de.robv.android.xposed.XC_MethodHook$Unhook@26c56b3]
ThanosS: hookIntentFireWall checkIntent OK:[de.robv.android.xposed.XC_MethodHook$Unhook@bfda470]
ThanosS: hookPackageManagerServiceAppSetting...
ThanosS: hookPackageManagerServiceAppSetting OK:[de.robv.android.xposed.XC_MethodHook$Unhook@1b953e9]
ThanosS: hookPackageManagerServiceCompSetting...
ThanosS: hookPackageManagerServiceCompSetting OK:[de.robv.android.xposed.XC_MethodHook$Unhook@2afe86e]
ThanosS: hookPackageManagerServiceInit...
ThanosS: hookPackageManagerServiceInit OK: [de.robv.android.xposed.XC_MethodHook$Unhook@cbab0f]
ThanosS: hookPackageManagerServiceSystemReady...
ThanosS: hookPackageManagerServiceSystemReady OK: [de.robv.android.xposed.XC_MethodHook$Unhook@170979c]
ThanosS: hookMediaFocus...
ThanosS: hookMediaFocus OK:[de.robv.android.xposed.XC_MethodHook$Unhook@ef61d7a]
ThanosS: hookIsVisibleRecentTask...
ThanosS: hookIsVisibleRecentTask...class:class com.android.server.wm.RecentTasks
ThanosS: hookIsVisibleRecentTask OK:[de.robv.android.xposed.XC_MethodHook$Unhook@fbd9188]
ThanosS: hookSuperVisorCleanUpTask...
ThanosS: hookSuperVisorCleanUpTask OK:[de.robv.android.xposed.XC_MethodHook$Unhook@d3e9721]
ThanosS: hookNotifyTaskCreated...
ThanosS: hookNotifyTaskCreated OK: [de.robv.android.xposed.XC_MethodHook$Unhook@e53ed07]
ThanosS: bindServiceLocked, unhooks [de.robv.android.xposed.XC_MethodHook$Unhook@d4c845d]
ThanosS: hookStartService, unhooks [de.robv.android.xposed.XC_MethodHook$Unhook@6d6e1d2, de.robv.android.xposed.XC_MethodHook$Unhook@cb852a3]
ThanosS: hookStartProcessLocked...
ThanosS: clazz=class com.android.server.am.ProcessList
ThanosS: processRecordClazz=class com.android.server.am.ProcessRecord
ThanosS: hostingRecordClazz=class com.android.server.am.HostingRecord
ThanosS: startProcessLocked=boolean com.android.server.am.ProcessList.startProcessLocked(com.android.server.am.ProcessRecord,com.android.server.am.HostingRecord,boolean,boolean,java.lang.String)
ThanosS: hookStartProcessLocked OK:de.robv.android.xposed.XC_MethodHook$Unhook@e520959
ThanosS: hookGetContentProviderImpl...
ThanosS: Method getContentProviderImpl: private android.app.ContentProviderHolder com.android.server.am.ActivityManagerService.getContentProviderImpl(android.app.IApplicationThread,java.lang.String,android.os.IBinder,int,java.lang.String,java.lang.String,boolean,int)
ThanosS: hookGetContentProviderImpl OK:de.robv.android.xposed.XC_MethodHook$Unhook@b9d491e
ThanosS: hookRemoveProcess...
ThanosS: clazz=class com.android.server.am.ProcessList
ThanosS: processRecordClazz=class com.android.server.am.ProcessRecord
ThanosS: removeLruProcessLocked=final void com.android.server.am.ProcessList.removeLruProcessLocked(com.android.server.am.ProcessRecord)
ThanosS: hookRemoveProcess OK:de.robv.android.xposed.XC_MethodHook$Unhook@97375ff
ThanosS: hookTaskSnapshotController...
ThanosS: hookTaskSnapshotController OK: [de.robv.android.xposed.XC_MethodHook$Unhook@290e215]
ThanosS: hookGetTaskSnapshot...
ThanosS: hookGetTaskSnapshot OK: [de.robv.android.xposed.XC_MethodHook$Unhook@dd0d92a]
ThanosS: hookOpsFinishOp, unhooks [de.robv.android.xposed.XC_MethodHook$Unhook@1bc6cb8]
ThanosS: hookCheckOp...
ThanosS: hookCheckOp OK:[de.robv.android.xposed.XC_MethodHook$Unhook@4aa8a91]
ThanosS: hookNoteOperation...
ThanosS: hookNoteOperation OK:[de.robv.android.xposed.XC_MethodHook$Unhook@ffb5df6]
ThanosS: hookNoteProxyOperation...
ThanosS: hookNoteProxyOperation OK:[de.robv.android.xposed.XC_MethodHook$Unhook@6ec25f7]
ThanosS: hookStartOperation...
ThanosS: hookStartOperation OK:[de.robv.android.xposed.XC_MethodHook$Unhook@a279c64]
ThanosS: mLruProcesses: []
ThanosS: AppGlobals.setContext: android.app.ContextImpl@e34ce3e
