### ISSUE TITLE
代收插件不适配太极

### ISSUE THREAD

**Issue by JiZhi-Error** [Tornaco/Thanox#156]
开机就直接崩，如需提供更多log可联系我，这个bug很好卡
2020-07-30 08:08:35.066 2062-2062/? E/ThanosS: PluginBridge  Error loading class java.lang.ClassNotFoundException: Didn't find class "github.tornaco.android.plugin.push.message.delegate.hooks.HookEntry" on path: DexPathList[[zip file "/data/system/thanos/data/u/0/plugins/github.tornaco.android.plugin.push.message.delegate.tp"],nativeLibraryDirectories=[/system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at github.tornaco.android.thanos.services.xposed.hooks.plugin.PluginBridge.invokeHandleLoadPackage(Unknown Source:141)
        at github.tornaco.android.thanos.services.xposed.hooks.plugin.PluginBridge.invokeHandleLoadPackage(Unknown Source:57)
        at github.tornaco.android.thanos.services.xposed.hooks.plugin.PluginBridge.handleLoadPackage(Unknown Source:15)
        at github.tornaco.android.thanos.services.xposed.XposedHookEntry.handleLoadPackage(Unknown Source:34)
        at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(SourceFile:34)
        at de.robv.android.xposed.callbacks.XC_LoadPackage.call(SourceFile:61)
        at de.robv.android.xposed.callbacks.XCallback.callAll(SourceFile:106)
        at me.weishu.exposed.ExposedBridge.ˏ(SourceFile:925)
        at me.weishu.exposed.ExposedBridge.loadModule(SourceFile:809)
        at me.weishu.exposed.ExposedBridge.initNative(Native Method)
        at me.weishu.exposed.ExposedBridge.init(SourceFile:219)
        at java.lang.reflect.Method.invoke(Native Method)
        at me.weishu.taichi.MagiskInit.O00000o(Unknown Source:238)
        at me.weishu.taichi.MagiskInit.O000000o(Unknown Source:0)
        at me.weishu.taichi.MagiskInit$3.invoke(Unknown Source:60)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy1.addService(Unknown Source)
        at android.os.ServiceManager.addService(ServiceManager.java:192)
        at android.os.ServiceManager.addService(ServiceManager.java:161)
        at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:2420)
2020-07-30 08:08:35.066 2062-2062/? E/ThanosS:     at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:769)
        at com.android.server.SystemServer.run(SystemServer.java:543)
        at com.android.server.SystemServer.main(SystemServer.java:382)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lgithub/tornaco/android/thanos/services/xposed/IXposedHook;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        		... 27 more
     Caused by: java.lang.ClassNotFoundException: github.tornaco.android.thanos.services.xposed.IXposedHook
        		... 30 more
[thanos.zip](https://github.com/Tornaco/Thanox/files/4998088/thanos.zip)
![image](https://user-images.githubusercontent.com/24365406/88866221-95201580-d23c-11ea-9747-a6f696838b76.png)

**Comment by Tornaco** [comment]
@JiZhi-Error OK
