### ISSUE TITLE
Unable to activate on android R

### ISSUE THREAD

**Issue by moelife-coder** [Tornaco/Thanox#165]
**Describe the bug（现象描述）**

Thanox is unable to be activated on android R using EdXposed, even if the module is selected in EdXposed manager

Thanox 在 Android R 上无法使用 EdXposed(YAHFA) 激活

**Version（发现问题的版本）:**
 - OS: Android 11
 - Version v2.0-alpha-1-c2471f9-prc

** Logs**（日志文件）
```
09-15 08:31:19.331  1632  1632 I EdXposed-Bridge: Loading modules from /data/app/~~RB8KtJ1DJ1jjKF7ZJD1PIA==/github.tornaco.android.thanos-kRjVKNxt6-LCbQ7J2wAGbA==/base.apk
09-15 08:31:19.455  1632  1632 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
09-15 08:31:19.510  1632  1632 E EdXposed-Bridge:     Failed to load class github.tornaco.android.thanos.services.xposed.XposedHookEntry
09-15 08:31:19.510  1632  1632 E EdXposed-Bridge: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
09-15 08:31:19.510  1632  1632 E EdXposed-Bridge: 	at github.tornaco.android.thanos.services.xposed.XposedHookEntry.initZygote(Unknown Source:18)
09-15 08:31:19.510  1632  1632 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:483)
09-15 08:31:19.510  1632  1632 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:349)
09-15 08:31:19.510  1632  1632 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp.proxy.BaseRouter.loadModulesSafely(BaseRouter.java:81)
09-15 08:31:19.510  1632  1632 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp.proxy.NormalProxy.forkSystemServerPre(NormalProxy.java:54)
09-15 08:31:19.510  1632  1632 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp.core.Main.forkSystemServerPre(Main.java:108)
09-15 08:31:19.510  1632  1632 E EdXposed-Bridge: 	at com.android.internal.os.Zygote.nativeForkSystemServer(Native Method)
09-15 08:31:19.510  1632  1632 E EdXposed-Bridge: 	at com.android.internal.os.Zygote.forkSystemServer(Zygote.java:465)
09-15 08:31:19.510  1632  1632 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.forkSystemServer(ZygoteInit.java:781)
09-15 08:31:19.510  1632  1632 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:920)
```

**Comment by Tornaco** [comment]
@moelife-coder Xposed补丁目前还在适配中，请关注后续版本。
