### ISSUE TITLE
Android 11点击正在运行和乖巧会软重启，后台启动功能消失

### ISSUE THREAD

**Issue by wanlyg** [Tornaco/Thanox#167]
**Describe the bug（现象描述）**
点击正在运行和乖巧会软重启，后台启动功能消失

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
点击xx个应用正在运行，软重启
点击乖巧模式，软重启
后台启动功能消失

**Expected behavior**（期望结果）
修复bug
**Screenshots**（截图）
无
**Version（发现问题的版本）:**
Android 11 (AOSP 改名)
Thanox v2.0-alpha03

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。

**Comment by wanlyg** [comment]
补充
Edxposed s版和y版均存在此问题
sdcard/Android/ 下无日志

上面的日志是点击了两次正在运行的日志
下面这个日志是点击乖巧模式软重启的日志

**Comment by Tornaco** [comment]
```
java.lang.NoSuchMethodError: No interface method isAppInactive(Ljava/lang/String;I)Z in class Landroid/app/usage/IUsageStatsManager; or its super classes (declaration of 'android.app.usage.IUsageStatsManager' appears in /system/framework/framework.jar)
	at github.tornaco.android.thanos.services.app.ActivityManagerService.isPackageIdle(Unknown Source:19)
	at github.tornaco.android.thanos.services.app.ActivityManagerStub.isPackageIdle(Unknown Source:2)
	at github.tornaco.android.thanos.core.app.IActivityManager$Stub.onTransact(Unknown Source:1768)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)

```

@wanlyg Android 11 IUsageStatsManager接口发生了变更。下个版本会处理。

New API:
```
    @UnsupportedAppUsage
    void setAppInactive(String packageName, boolean inactive, int userId);
    @UnsupportedAppUsage
    boolean isAppInactive(String packageName, int userId, String callingPackage);
```
