### ISSUE TITLE
Android 11 活动管理/广播接收管理器/服务管理 打开无内容

### ISSUE THREAD

**Issue by wanlyg** [Tornaco/Thanox#169]
Describe the bug（现象描述）
应用详情页面，活动管理 广播接收管理器 服务管理 打开无内容

To Reproduce（如何复现）
Steps to reproduce the behavior:（复现步骤）
点击应用列表，随便点进一个应用。点击活动管理/广播接收管理器/服务管理 打开无内容

Expected behavior（期望结果）
修复bug
Screenshots（截图）
无
Version（发现问题的版本）:
Android 11 (AOSP 改名)
Thanox v2.0-alpha04

Additional context（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。
1600577691124|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1600577691126|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1600577691127|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1600577691127|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1600577691129|D|ThanoxApp|onAttach
1600577691129|D|ThanoxApp|onCreate
1600577691130|D|ThanoxApp|onActivityCreated
1600577691143|V|ThanoxApp|isPaid? true
1600577691157|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1600577692843|D|ThanoxApp|onAttach
1600577692843|D|ThanoxApp|onCreate
1600577692874|E|ThanoxApp|Error getAllInstalledPlugin
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.util.ArrayMap.get(java.lang.Object)' on a null object reference
	at android.os.Parcel.readSquashed(Parcel.java:2082)
	at android.content.pm.ApplicationInfo$1.createFromParcel(ApplicationInfo.java:1776)
	at android.content.pm.ApplicationInfo$1.createFromParcel(ApplicationInfo.java:1773)
	at github.tornaco.android.nitro.framework.host.manager.data.ParcelUtils.unmarshall(Unknown Source:4)
	at github.tornaco.android.nitro.framework.host.manager.data.converter.ApplicationInfoConverter.activityInfoFromBytes(Unknown Source:2)
	at github.tornaco.android.nitro.framework.host.manager.data.source.local.PluginAppDao_Impl.loadByPackageName(Unknown Source:62)
	at github.tornaco.android.nitro.framework.host.manager.data.Repo.getAllInstalledPlugin(Unknown Source:53)
	at github.tornaco.android.nitro.framework.Nitro.getAllInstalledPlugin(Unknown Source:0)
	at github.tornaco.android.thanos.main.NavViewModel.loadPluginFeatures(Unknown Source:33)
	at github.tornaco.android.thanos.main.PluginFragment.setupViewModel(Unknown Source:22)
	at github.tornaco.android.thanos.main.PluginFragment.onCreateView(Unknown Source:10)
	at androidx.fragment.app.Fragment.performCreateView(Unknown Source:15)
	at androidx.fragment.app.h.t0(:8)
	at androidx.fragment.app.h.r0(Unknown Source:49)
	at androidx.fragment.app.h.s0(Unknown Source:42)
	at androidx.fragment.app.a.u(:4)
	at androidx.fragment.app.h.e0(:7)
	at androidx.fragment.app.h.y0(Unknown Source:88)
	at androidx.fragment.app.h.c0(:2)
	at androidx.fragment.app.h.X(Unknown Source:9)
	at androidx.fragment.app.h.r(Unknown Source:6)
	at androidx.fragment.app.d.c(Unknown Source:4)
	at androidx.fragment.app.FragmentActivity.onStart(Unknown Source:15)
	at androidx.appcompat.app.AppCompatActivity.onStart(Unknown Source:0)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8024)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at com.osama.firecrasher.e.run(Unknown Source:87)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callStaticMethod(XposedHelpers.java:1308)
	at tiiehenry.xp.grapcrash.CrashHandler.lambda$insert$0(CrashHandler.java:39)
	at tiiehenry.xp.grapcrash.-$$Lambda$CrashHandler$0aI9OlK525o-9UB6htkRKKZ50C0.run(Unknown Source:0)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

1600577692877|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1600577692877|D|ThanoxApp|onActivityCreated
1600577693592|V|ThanoxApp|isPaid? true
1600577693608|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1600577694079|D|ThanoxApp|onDestroy
1600577695280|V|ThanoxApp|isPaid? true
1600577695295|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F

**Comment by moelife-coder** [comment]
同样的问题
Log(很长，截取了一小段，其他的基本上是在重复):
```
09-20 15:02:43.878  2046  2059 E Thanox-Core: Fail retrieve field from legacy: public android.content.pm.ApplicationInfo github.tornaco.android.thanos.core.pm.Package.applicationInfo
09-20 15:02:43.878  2046  2059 E Thanox-Core: java.lang.NoSuchFieldError: com.android.server.pm.parsing.pkg.PackageImpl#applicationInfo
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at util.XposedHelpers.findField(Unknown Source:45)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at util.XposedHelpers.getObjectField(Unknown Source:4)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.core.pm.Package.fromLegacy(Unknown Source:43)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PackageManagerServiceProxy.getPackage(Unknown Source:95)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PkgManagerService.getPackageInternal(Unknown Source:26)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PkgManagerService.getActivitiesCount(Unknown Source:8)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PkgManagerStub.getActivitiesCount(Unknown Source:2)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.core.pm.IPkgManager$Stub.onTransact(Unknown Source:668)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at android.os.Binder.execTransactInternal(Binder.java:1154)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at android.os.Binder.execTransact(Binder.java:1123)
09-20 15:02:43.878  2046  2059 E Thanox-Core: Fail retrieve field from legacy: public long[] github.tornaco.android.thanos.core.pm.Package.mLastPackageUsageTimeInMills
09-20 15:02:43.878  2046  2059 E Thanox-Core: java.lang.NoSuchFieldError: com.android.server.pm.parsing.pkg.PackageImpl#mLastPackageUsageTimeInMills
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at util.XposedHelpers.findField(Unknown Source:45)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at util.XposedHelpers.getObjectField(Unknown Source:4)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.core.pm.Package.fromLegacy(Unknown Source:43)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PackageManagerServiceProxy.getPackage(Unknown Source:95)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PkgManagerService.getPackageInternal(Unknown Source:26)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PkgManagerService.getActivitiesCount(Unknown Source:8)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PkgManagerStub.getActivitiesCount(Unknown Source:2)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.core.pm.IPkgManager$Stub.onTransact(Unknown Source:668)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at android.os.Binder.execTransactInternal(Binder.java:1154)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at android.os.Binder.execTransact(Binder.java:1123)
09-20 15:02:43.878  2046  2059 E Thanox-Core: Fail retrieve field from legacy: public java.lang.String github.tornaco.android.thanos.core.pm.Package.mSharedUserId
09-20 15:02:43.878  2046  2059 E Thanox-Core: java.lang.NoSuchFieldError: com.android.server.pm.parsing.pkg.PackageImpl#mSharedUserId
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at util.XposedHelpers.findField(Unknown Source:45)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at util.XposedHelpers.getObjectField(Unknown Source:4)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.core.pm.Package.fromLegacy(Unknown Source:43)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PackageManagerServiceProxy.getPackage(Unknown Source:95)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PkgManagerService.getPackageInternal(Unknown Source:26)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PkgManagerService.getActivitiesCount(Unknown Source:8)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PkgManagerStub.getActivitiesCount(Unknown Source:2)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.core.pm.IPkgManager$Stub.onTransact(Unknown Source:668)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at android.os.Binder.execTransactInternal(Binder.java:1154)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at android.os.Binder.execTransact(Binder.java:1123)
09-20 15:02:43.878  2046  2059 E Thanox-Core: Fail retrieve field from legacy: public int github.tornaco.android.thanos.core.pm.Package.mSharedUserLabel
09-20 15:02:43.878  2046  2059 E Thanox-Core: java.lang.NoSuchFieldError: com.android.server.pm.parsing.pkg.PackageImpl#mSharedUserLabel
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at util.XposedHelpers.findField(Unknown Source:45)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at util.XposedHelpers.getObjectField(Unknown Source:4)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.core.pm.Package.fromLegacy(Unknown Source:43)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PackageManagerServiceProxy.getPackage(Unknown Source:95)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PkgManagerService.getPackageInternal(Unknown Source:26)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PkgManagerService.getActivitiesCount(Unknown Source:8)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PkgManagerStub.getActivitiesCount(Unknown Source:2)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.core.pm.IPkgManager$Stub.onTransact(Unknown Source:668)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at android.os.Binder.execTransactInternal(Binder.java:1154)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at android.os.Binder.execTransact(Binder.java:1123)
09-20 15:02:43.878  2046  2059 E Thanox-Core: Fail retrieve field from legacy: public int github.tornaco.android.thanos.core.pm.Package.mVersionCode
09-20 15:02:43.878  2046  2059 E Thanox-Core: java.lang.NoSuchFieldError: com.android.server.pm.parsing.pkg.PackageImpl#mVersionCode
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at util.XposedHelpers.findField(Unknown Source:45)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at util.XposedHelpers.getObjectField(Unknown Source:4)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.core.pm.Package.fromLegacy(Unknown Source:43)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PackageManagerServiceProxy.getPackage(Unknown Source:95)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PkgManagerService.getPackageInternal(Unknown Source:26)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PkgManagerService.getActivitiesCount(Unknown Source:8)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PkgManagerStub.getActivitiesCount(Unknown Source:2)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.core.pm.IPkgManager$Stub.onTransact(Unknown Source:668)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at android.os.Binder.execTransactInternal(Binder.java:1154)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at android.os.Binder.execTransact(Binder.java:1123)
09-20 15:02:43.878  2046  2059 E Thanox-Core: Fail retrieve field from legacy: public java.lang.String github.tornaco.android.thanos.core.pm.Package.mVersionName
09-20 15:02:43.878  2046  2059 E Thanox-Core: java.lang.NoSuchFieldError: com.android.server.pm.parsing.pkg.PackageImpl#mVersionName
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at util.XposedHelpers.findField(Unknown Source:45)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at util.XposedHelpers.getObjectField(Unknown Source:4)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.core.pm.Package.fromLegacy(Unknown Source:43)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PackageManagerServiceProxy.getPackage(Unknown Source:95)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PkgManagerService.getPackageInternal(Unknown Source:26)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PkgManagerService.getActivitiesCount(Unknown Source:8)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.services.pm.PkgManagerStub.getActivitiesCount(Unknown Source:2)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at github.tornaco.android.thanos.core.pm.IPkgManager$Stub.onTransact(Unknown Source:668)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at android.os.Binder.execTransactInternal(Binder.java:1154)
09-20 15:02:43.878  2046  2059 E Thanox-Core:   at android.os.Binder.execTransact(Binder.java:1123)
```

**Comment by Tornaco** [comment]
@wanlyg @moelife-coder OK.
