### ISSUE TITLE
Android 11 无限软重启

### ISSUE THREAD

**Issue by wanlyg** [Tornaco/Thanox#172]
Describe the bug（现象描述）
Android 11无限软重启

To Reproduce（如何复现）
Steps to reproduce the behavior:（复现步骤）
更新到 2.0-beta1-4 勾选Edxposed选择后重启

Expected behavior（期望结果）
修复bug
Screenshots（截图）
无
Version（发现问题的版本）:
Android 11 (AOSP 改名)
Thanox V2.0-beta1-4-78fba4b-prc

Additional context（其他信息）
Add any other context about the problem here.（其他的补充信息）
以下为截取自thanox-core.log

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里
for name: com.google.android.gsf.gservices, providerInfo is null
2020-09-26 07:21:07.320 W/Thanox-Core: getContentProviderImpl fail resolve provider for name: com.google.android.gsf.gservices, providerInfo is null
2020-09-26 07:21:07.611 W/Thanox-Core: getContentProviderImpl fail resolve provider for name: com.google.android.gsf.gservices, providerInfo is null
2020-09-26 07:21:07.620 W/Thanox-Core: getContentProviderImpl fail resolve provider for name: com.google.android.gsf.gservices, providerInfo is null
2020-09-26 07:21:08.395 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2020-09-26 07:21:08.451 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2020-09-26 07:21:10.162 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2020-09-26 07:21:10.249 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2020-09-26 07:21:10.787 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2020-09-26 07:21:10.797 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2020-09-26 07:21:11.118 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2020-09-26 07:21:11.277 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2020-09-26 07:21:11.309 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2020-09-26 07:21:11.348 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2020-09-26 07:21:11.403 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2020-09-26 07:21:11.406 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2020-09-26 07:21:11.415 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2020-09-26 07:21:11.443 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2020-09-26 07:21:11.485 W/Thanox-Core: getContentProviderImpl fail resolve provider for name: com.google.android.googlequicksearchbox.GsaPublicContentProvider, providerInfo is null
2020-09-26 07:21:11.674 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2020-09-26 07:21:11.692 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2020-09-26 07:21:12.524 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2020-09-26 07:21:12.526 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2020-09-26 07:21:13.761 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2020-09-26 07:21:15.275 W/Thanox-Core: publishSystemReadyFactsIfNeed
2020-09-26 07:21:17.989 W/Thanox-Core: onPlaybackConfigChanged, clean up currentFocusedPackageNames.
2020-09-26 07:21:26.777 W/Thanox-Core: Adding TV input service @java.lang.Throwable
	at github.tornaco.android.thanos.services.xposed.hooks.ServiceManagerRegistry$1.beforeHookedMethod(Unknown Source:26)
	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:360)
	at SandHookerNew_2nmeb0fr8t8stpg9ff8gpighe.hook(Unknown Source:62)
	at github.tornaco.android.thanos.services.ThanosService.publishBinderService(Unknown Source:0)
	at github.tornaco.android.thanos.services.ThanosService.publishBinderService(Unknown Source:1)
	at github.tornaco.android.thanos.services.ThanosService.onStart(Unknown Source:101)
	at github.tornaco.android.thanos.services.BootStrap.start(Unknown Source:12)
	at github.tornaco.android.thanos.services.xposed.hooks.AMSBasicRegistry$1.beforeHookedMethod(Unknown Source:13)
	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:360)
	at SandHookerNew_4d0upk0tf7q8f9b5ho838bonu.hook(Unknown Source:46)
	at com.android.server.am.ActivityManagerService.access$1000(ActivityManagerService.java:415)
	at com.android.server.am.ActivityManagerService$Lifecycle.onStart(ActivityManagerService.java:2356)
	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:178)
	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:165)
	at com.android.server.am.ActivityManagerService$Lifecycle.startService(ActivityManagerService.java:2351)
	at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:763)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:185)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:379)
	at SandHookerNew_7ndub2ia0436di2jdu8pe9pmuj.hook(Unknown Source:51)
	at com.android.server.SystemServer.run(SystemServer.java:593)
	at com.android.server.SystemServer.main(SystemServer.java:411)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)

2020-09-26 07:21:26.779 W/Thanox-Core: Thanos stub: github.tornaco.android.thanos.services.ThanosServiceStub@9be7749@thanos@tornaco:dfa99ff9-bdc2-3f96-95cf-e7d2ed5c2eca
2020-09-26 07:21:26.779 W/Thanox-Core: Adding TV input service @java.lang.Throwable
	at github.tornaco.android.thanos.services.xposed.hooks.ServiceManagerRegistry$1.beforeHookedMethod(Unknown Source:26)
	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:360)
	at SandHookerNew_1lh8u3qr4jt920dlcv75s6j2ao.hook(Unknown Source:69)
	at android.os.ServiceManager.addService(ServiceManager.java:180)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:175)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:379)
	at SandHookerNew_2nmeb0fr8t8stpg9ff8gpighe.hook(Unknown Source:62)
	at github.tornaco.android.thanos.services.ThanosService.publishBinderService(Unknown Source:0)
	at github.tornaco.android.thanos.services.ThanosService.publishBinderService(Unknown Source:1)
	at github.tornaco.android.thanos.services.ThanosService.onStart(Unknown Source:101)
	at github.tornaco.android.thanos.services.BootStrap.start(Unknown Source:12)
	at github.tornaco.android.thanos.services.xposed.hooks.AMSBasicRegistry$1.beforeHookedMethod(Unknown Source:13)
	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:360)
	at SandHookerNew_4d0upk0tf7q8f9b5ho838bonu.hook(Unknown Source:46)
	at com.android.server.am.ActivityManagerService.access$1000(ActivityManagerService.java:415)
	at com.android.server.am.ActivityManagerService$Lifecycle.onStart(ActivityManagerService.java:2356)
	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:178)
	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:165)
	at com.android.server.am.ActivityManagerService$Lifecycle.startService(ActivityManagerService.java:2351)
	at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:763)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:185)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:379)
	at SandHookerNew_7ndub2ia0436di2jdu8pe9pmuj.hook(Unknown Source:51)
	at com.android.server.SystemServer.run(SystemServer.java:593)
	at com.android.server.SystemServer.main(SystemServer.java:411)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)

2020-09-26 07:21:26.781 W/Thanox-Core: Thanos stub: github.tornaco.android.thanos.services.ThanosServiceStub@9be7749@thanos@tornaco:dfa99ff9-bdc2-3f96-95cf-e7d2ed5c2eca
2020-09-26 07:21:26.785 W/Thanox-Core: onAttachActivityManagerServiceProxy: ActiveServicesProxy{host=com.android.server.am.ActiveServices@2ee3f05}
2020-09-26 07:21:26.786 W/Thanox-Core: onAttachActivityManagerServiceProxy: ActivityManagerServiceProxy{host=com.android.server.am.ActivityManagerService@31cde10}
2020-09-26 07:21:27.149 W/Thanox-Core: getBaseFile not exists, skip load: plugins_conf
2020-09-26 07:21:27.178 W/Thanox-Core: getBaseFile not exists, skip load: component_replacements
2020-09-26 07:21:27.179 W/Thanox-Core: getBaseFile not exists, skip load: priv_pkg_fields
2020-09-26 07:21:27.180 W/Thanox-Core: getAllFieldsProfilesFromFile, parse: /data/system/thanos/data/u/0/priv_fields, out: null
2020-09-26 07:21:27.191 W/Thanox-Core: getBaseFile not exists, skip load: op_template
2020-09-26 07:21:27.453 W/Thanox-Core: ProfileService server handler: Handler (android.os.Handler) {e9538a8}
2020-09-26 07:21:36.522 W/Thanox-Core: onPackageManagerServiceAttach: PackageManagerServiceProxy{host=com.android.server.pm.PackageManagerService@daf942}
2020-09-26 07:21:40.243 W/Thanox-Core: onPackageManagerServiceAttach: PackageManagerServiceProxy{host=com.android.server.pm.PackageManagerService@daf942}
2020-09-26 07:21:40.250 W/Thanox-Core: StartDb: using file db for debug build: /data/system/thanos/sec_data/u/0/db/start.db
2020-09-26 07:21:40.262 W/Thanox-Core: Init pkg pool for user: 机主 with id: 0
2020-09-26 07:21:42.047 W/Thanox-Core: thanosAppUid=[10252]
2020-09-26 07:21:43.104 W/Thanox-Core: getContentProviderImpl fail resolve provider for name: com.android.calendar, providerInfo is null
2020-09-26 07:21:43.129 W/Thanox-Core: getContentProviderImpl fail resolve provider for name: com.android.calendar, providerInfo is null
2020-09-26 07:21:43.862 W/Thanox-Core: getContentProviderImpl fail resolve provider for name: com.android.contacts, providerInfo is null
2020-09-26 07:21:44.124 W/Thanox-Core: ====== PkgPool-0 dump start ======
2020-09-26 07:21:44.126 W/Thanox-Core: PkgPool app: AppInfo(pkgName=com.android.printspooler, iconUrl=null, appLabel=打印处理服务, versionCode=30, versionName=11, flags=2, uid=10171, debuggable=false, minSdkVersion=30, targetSdkVersion=30, state=0, idle=false, isDummy=false, isSelected=false, str=null, obj=null, arg1=0, arg2=0, iconDrawable=0)

**Comment by wanlyg** [comment]
另外push插件似乎也发生了崩溃,这个崩溃似乎在几个版本前就发生了
Thanox-Core: PluginBridge  Loading modules from: /data/system/thanos/data/u/0/plugins/github.tornaco.android.plugin.push.message.delegate.tp, loading pkg: android
Thanox-Core: PluginBridge  Loading class github.tornaco.android.plugin.push.message.delegate.hooks.HookEntry
Thanox-Core: PluginBridge  moduleInstance github.tornaco.android.plugin.push.message.delegate.hooks.HookEntry@aa1bd4a
Thanox-Core: PluginBridge  Error loading class java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at github.tornaco.android.plugin.push.message.delegate.hooks.HookEntry.handleLoadPackage(:16)
	at java.lang.reflect.Method.invoke(Native Method)
	at util.ReflectionUtils.invokeMethod(Unknown Source:4)
	at github.tornaco.android.thanos.services.xposed.hooks.plugin.PluginBridge.invokeHandleLoadPackage(Unknown Source:174)
	at github.tornaco.android.thanos.services.xposed.hooks.plugin.PluginBridge.invokeHandleLoadPackage(Unknown Source:57)
	at github.tornaco.android.thanos.services.xposed.hooks.plugin.PluginBridge.handleLoadPackage(Unknown Source:15)
	at github.tornaco.android.thanos.services.xposed.XposedHookEntry.handleLoadPackage(Unknown Source:34)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:37)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117)
	at com.elderdrivers.riru.edxp._hooker.impl.StartBootstrapServices.beforeHookedMethod(StartBootstrapServices.java:36)
	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:360)
	at SandHookerNew_7ndub2ia0436di2jdu8pe9pmuj.hook(Unknown Source:51)
	at com.android.server.SystemServer.run(SystemServer.java:590)
	at com.android.server.SystemServer.main(SystemServer.java:408)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)

问题 #170 可能与此崩溃有关，如果需要全部(全新)日志，请@我

**Comment by Tornaco** [comment]
@wanlyg 给个全的日志吧，最好能adb抓一个反复开机过程的完整日志

**Comment by wanlyg** [comment]
完整的thanox日志和adb日志
[logging.zip](https://github.com/Tornaco/Thanox/files/5286031/logging.zip)

[adb-logcat.zip](https://github.com/Tornaco/Thanox/files/5286034/adb-logcat.zip)
我删除了thanox日志中PkgPool-0 dump出的所有程序
@Tornaco

**Comment by Tornaco** [comment]
FATAL
```
onApplicationCrashing: crash system_server null java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.android.launcher3 (/system/system_ext/priv-app/Launcher3QuickStep): android.permission.WRITE_SECURE_SETTINGS, com.android.launcher3 (/system/system_ext/priv-app/Launcher3QuickStep): android.permission.CONTROL_REMOTE_APP_TRANSITION_ANIMATIONS, com.android.launcher3 (/system/system_ext/priv-app/Launcher3QuickStep): android.permission.BIND_APPWIDGET}
	at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:4554)
	at com.android.server.pm.permission.PermissionManagerService.access$500(PermissionManagerService.java:178)
	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.systemReady(PermissionManagerService.java:4637)
	at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:185)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:379)
	at SandHookerNew_3md2db65g9mutmlhpuddt42asb.hook(Unknown Source:46)
	at com.android.server.SystemServer.startOtherServices(SystemServer.java:2201)
	at com.android.server.SystemServer.run(SystemServer.java:595)
	at com.android.server.SystemServer.main(SystemServer.java:411)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
```

**Comment by Tornaco** [comment]
@wanlyg  你把包怎么了。。我看日志里各种摘不到包。以及跟权限相关的错误
```
09-26 09:24:47.565 W/PackageManager( 7871): Privileged permission android.permission.CONTROL_REMOTE_APP_TRANSITION_ANIMATIONS for package com.android.launcher3 (/system/system_ext/priv-app/Launcher3QuickStep) not in privapp-permissions whitelist
09-26 09:24:47.565 W/PackageManager( 7871): Privileged permission android.permission.BIND_APPWIDGET for package com.android.launcher3 (/system/system_ext/priv-app/Launcher3QuickStep) not in privapp-permissions whitelist
09-26 09:24:47.565 W/PackageManager( 7871): Privileged permission android.permission.WRITE_SECURE_SETTINGS for package com.android.launcher3 (/system/system_ext/priv-app/Launcher3QuickStep) not in privapp-permissions whitelist
```

**Comment by wanlyg** [comment]
这个Android11 rom是测试版的，并且是我没清数据从Android10强刷上的，跟这个无限重启有关系吗？有什么影响吗？😱 @Tornaco

**Comment by Tornaco** [comment]
不激活thanox可以启动？ @wanlyg

**Comment by wanlyg** [comment]
可以正常使用，而且上一个版本v2.0-alpha04 v2.0-alpha03也都正常使用

**Comment by Tornaco** [comment]
@wanlyg  OK .. 我再看下改了啥

**Comment by Tornaco** [comment]
@wanlyg 帮忙抓个不激活thanox的adb完整开机日志

**Comment by wanlyg** [comment]
来了来了
[adb_logcat.zip](https://github.com/Tornaco/Thanox/files/5286799/adb_logcat.zip)

**Comment by Tornaco** [comment]
[thanox_2.0-alpha04-19-7248c61-7248c61b0b7b7d34ca3ea6a9233a49023ad3cfcc-prc.apk.zip](https://github.com/Tornaco/Thanox/files/5292085/thanox_2.0-alpha04-19-7248c61-7248c61b0b7b7d34ca3ea6a9233a49023ad3cfcc-prc.apk.zip)

@wanlyg 有条件的话试试这个、、、

**Comment by wanlyg** [comment]
ok，待会儿反馈

**Comment by Tornaco** [comment]
@wanlyg 不知道版本号能不能直接安装上，不行我重新给你编一个版本号高的。

**Comment by wanlyg** [comment]
我有核心破解，已经正常开机了，可以正常使用

**Comment by Tornaco** [comment]
@wanlyg 我把代码回退了。排查下是哪次提交导致的，rou'y肉眼看不出问题。  再试试这个：

[thanox_2.0-beta1-prc.apk.zip](https://github.com/Tornaco/Thanox/files/5292677/thanox_2.0-beta1-prc.apk.zip)

**Comment by wanlyg** [comment]
这个翻车了，和之前一样无限软重启，如果不能排查的话可以多发几个版本，我一起试 @Tornaco

**Comment by Tornaco** [comment]
@wanlyg  好。。稍等编译比较慢

**Comment by Tornaco** [comment]
[thanox_2.0-alpha04-25-89bdd81-89bdd81cd5cd407ad5fc8f758847a8b7ae55b326-prc.apk.zip](https://github.com/Tornaco/Thanox/files/5292817/thanox_2.0-alpha04-25-89bdd81-89bdd81cd5cd407ad5fc8f758847a8b7ae55b326-prc.apk.zip)

@wanlyg 先这个吧

**Comment by wanlyg** [comment]
这个是正常的 。

**Comment by Tornaco** [comment]
@wanlyg 好的，辛苦了、、快逼近了。

**Comment by Tornaco** [comment]
[thanox_2.0-beta1-7-204b8fe-dirty-prc.apk.zip](https://github.com/Tornaco/Thanox/files/5293034/thanox_2.0-beta1-7-204b8fe-dirty-prc.apk.zip)

@wanlyg  今天最后一个，不行明天再搞了

**Comment by wanlyg** [comment]
ok!

**Comment by wanlyg** [comment]
这次翻车了。

**Comment by Tornaco** [comment]
@wanlyg 😂

**Comment by Tornaco** [comment]
[thanox_2.0-alpha04-28-1bd35f8-1bd35f825b18edf5b1ba715b4ae33a7b8f79f693-prc.apk.zip](https://github.com/Tornaco/Thanox/files/5295733/thanox_2.0-alpha04-28-1bd35f8-1bd35f825b18edf5b1ba715b4ae33a7b8f79f693-prc.apk.zip)

@wanlyg

**Comment by wanlyg** [comment]
这次没问题，可以用

**Comment by Tornaco** [comment]
[thanox_2.0-97-204b8fe-dirty-prc.apk.zip](https://github.com/Tornaco/Thanox/files/5296628/thanox_2.0-97-204b8fe-dirty-prc.apk.zip)


@wanlyg finally..

**Comment by wanlyg** [comment]
翻车了。

**Comment by Tornaco** [comment]
@wanlyg  见鬼了。。再看看这俩。:x
[Thanox-Tests.zip](https://github.com/Tornaco/Thanox/files/5299333/Thanox-Tests.zip)

**Comment by wanlyg** [comment]
两个都没问题，到目前为止，所有使用新图标(隐匿和乖巧)的都翻车了，所有使用旧图标的都没问题

**Comment by Tornaco** [comment]
@wanlyg 不对劲。。我在研究将研究。。改个图不至于。。

**Comment by Tornaco** [comment]
[thanox_2.0-beta1-prc-80256753.apk.zip](https://github.com/Tornaco/Thanox/files/5299614/thanox_2.0-beta1-prc-80256753.apk.zip)

这个呢，这个是基于上个提交，改了几张图。
@wanlyg  辛苦了

**Comment by wanlyg** [comment]
这个没问题。

**Comment by Tornaco** [comment]
> @wanlyg 我把代码回退了。排查下是哪次提交导致的，rou'y肉眼看不出问题。 再试试这个：
> 
> [thanox_2.0-beta1-prc.apk.zip](https://github.com/Tornaco/Thanox/files/5292677/thanox_2.0-beta1-prc.apk.zip)

@wanlyg 这个和上面昨晚发的是一样的版本。。一个有问题一个没问题。。你试试再重启一次呢？会不会是其他原因导致的。

**Comment by wanlyg** [comment]
我擦，我找找看

**Comment by wanlyg** [comment]
此问题在删除/data/thanos重启后消失。
怀疑配置文件导致
