### ISSUE TITLE
bug冻结应用后打开会导致手机锁屏

### ISSUE THREAD

**Issue by Achiesama** [Tornaco/Thanox#181]
**黑屏锁屏**

冻结应用后打开会导致手机黑屏锁屏。

冻结应用。
（复现步骤）
1. 进入智能冻结（进入XXX）
2. 点击加号（点击XXX）
3. 选择任意一个应用（下滑到XXX）
4. 返回进行点击（发现错误XXX）
5. 黑屏锁屏
6.开锁后进入冻结软件，关闭冻结软件后黑屏锁屏，解锁后关闭冻结软件。

**Screenshots**（截图）
![Screenshot_20201017-212008051](https://user-images.githubusercontent.com/44689896/96338157-c8957200-10be-11eb-9d71-06be77048db7.jpg)
![Screenshot_20201017-212009867](https://user-images.githubusercontent.com/44689896/96338163-cd5a2600-10be-11eb-9440-e33873fede48.jpg)
![Screenshot_20201017-212033](https://user-images.githubusercontent.com/44689896/96338167-d3e89d80-10be-11eb-96e3-86b5c4aa6674.png)
问题录像[录屏](https://drive.google.com/file/d/1-iHpGtqNNzfkJxILLQtEWD09QcIWTFCk/view?usp=drivesdk) 

.（通过截图更好的解释你的问题）

**Version（发现问题的版本）:**
 - OS: [evolution-x. Android 10]
 - Version [版本 2.0-4-0e2a340-prc］

**Additional context**（其他信息）
系统崩溃日志https://del.dog/prefimewep.（其他的补充信息）

** 

> Logs**（日志文件）
java.lang.NullPointerException: Attempt to read from field 'int com.android.server.wm.WindowState.mOwnerUid' on a null object reference
	at android.os.Parcel.createException(Parcel.java:2077)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at android.app.IActivityTaskManager$Stub$Proxy.finishActivity(IActivityTaskManager.java:4386)
	at android.app.Activity.finish(Activity.java:6243)
	at android.app.Activity.finish(Activity.java:6267)
	at github.tornaco.practice.honeycomb.locker.ui.verify.PatternLockVerifyFragment$4.onPropertyChanged(Unknown Source:14)
	at androidx.databinding.p$a.a(:1)
	at androidx.databinding.c.h(Unknown Source:20)
	at androidx.databinding.c.i(:1)
	at androidx.databinding.c.d(:1)
	at androidx.databinding.a.notifyChange(Unknown Source:12)
	at androidx.databinding.ObservableBoolean.c(Unknown Source:6)
	at github.tornaco.practice.honeycomb.locker.ui.verify.VerifyViewModel.pass(Unknown Source:18)
	at github.tornaco.practice.honeycomb.locker.ui.verify.VerifyViewModel.verify(Unknown Source:11)
	at github.tornaco.practice.honeycomb.locker.ui.binding.PatternLockViewBindings$1.onComplete(Unknown Source:8)
	at com.andrognito.patternlockview.PatternLockView.onTouchEvent(:5)
	at android.view.View.dispatchTouchEvent(View.java:13961)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:465)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1850)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4011)
	at androidx.appcompat.d.i.dispatchTouchEvent(Unknown Source:2)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
	at android.view.View.dispatchPointerEvent(View.java:14220)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5657)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5455)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5117)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5174)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7688)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7657)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7618)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7813)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:189)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.osama.firecrasher.e.run(Unknown Source:64)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7398)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.DisplayContent.lambda$new$2$DisplayContent(DisplayContent.java:628)
	at com.android.server.wm.-$$Lambda$DisplayContent$hRKjZwmneu0T85LNNY6_Zcs4gKM.accept(Unknown Source:4)
	at com.android.server.wm.WindowContainer$ForAllWindowsConsumerWrapper.apply(WindowContainer.java:1172)
	at com.android.server.wm.WindowContainer$ForAllWindowsConsumerWrapper.apply(WindowContainer.java:1162)
	at com.android.server.wm.WindowState.applyInOrderWithImeWindows(WindowState.java:4273)

	文件https://cowtransfer.com/s/1b54a9f398d340

务必将截取到的日志文件发到该issue里。

**Comment by Achiesama** [comment]
换了一个rom，目前还没出现这个问题
