### ISSUE TITLE
设备不定时自动重启

### ISSUE THREAD

**Issue by txw-yates** [Tornaco/Thanox#190]
现象描述：
安装thanox后，解锁设备后会偶尔会重启

如何复现：
安装thanox，放置一段时间后，解锁手机就会触发自动重启

期望结果：
解锁可以正常进入桌面

发现问题的版本：
手机：一加8t
系统：oxygen 11.0.5.6 欧版
thanox：v2.0-beta2
edxposed：0.5.6（4565 YAHFA）
magisk：21.1

** Logs**（日志文件）
![image](https://user-images.githubusercontent.com/23112008/99945745-2305aa80-2db0-11eb-99b8-a969446710b6.png)

**Comment by Tornaco** [comment]
@txw-yates 能否提供完整日志文件，多谢~

**Comment by txw-yates** [comment]
是要哪个目录下的文件，昨天因为不断重启卸载了，我在装上试试

> @txw-yates 能否提供完整日志文件，多谢~

**Comment by txw-yates** [comment]
@Tornaco 是要哪个目录下的文件，昨天因为不断重启卸载了，我在装上试试

**Comment by txw-yates** [comment]
[logging.zip](https://github.com/Tornaco/Thanox/files/5588395/logging.zip)
这个是整个logging文件夹

**Comment by Tornaco** [comment]
```
2020-11-24 16:26:55.819 E/Thanox-Core: onApplicationCrashing: crash system_server null java.lang.InternalError: Put 'Ljava/lang/Boolean;' that is not instance of field 'Lcom/android/server/am/ProcessRecord;' in 'Lcom/android/server/am/ContentProviderRecord;'
	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:8382)
	at EdHooker_.hook(Unknown Source:243)
	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:8568)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2443)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3282)
	at android.os.Binder.execTransactInternal(Binder.java:1165)
	at android.os.Binder.execTransact(Binder.java:1134)
```

**Comment by Tornaco** [comment]
@txw-yates Thanks。 日志里确实看到关键错误了，辛苦在提供下设备上的 `/framework/services.jar` 文件。

**Comment by txw-yates** [comment]
`/framework/services.jar`，这个是直接在根目录下吗，根目录下没有找到这个文件

**Comment by txw-yates** [comment]
[services.jar.zip](https://github.com/Tornaco/Thanox/files/5588456/services.jar.zip)
这个是` /system/framework/services.jar`这个文件，不知道对不对

**Comment by Tornaco** [comment]
@txw-yates 是的，晚一些发测试版，辛苦再帮忙测试下是否OK。

**Comment by txw-yates** [comment]
ok，到时候我在装了测一下

**Comment by wanlyg** [comment]
@Tornaco 插一个题外话，edxp在新版模块中关闭了模块对/data/system的权限，理由是容易被检测

**Comment by Tornaco** [comment]
[thanox_2.1-4-f795802-prc.apk.zip](https://github.com/Tornaco/Thanox/files/5589685/thanox_2.1-4-f795802-prc.apk.zip)


辛苦试试这个版本~

**Comment by Tornaco** [comment]
> @Tornaco 插一个题外话，edxp在新版模块中关闭了模块对/data/system的权限，理由是容易被检测

OK，后续如果有必要可以尝试进行迁移。因为目前Thanox核心服务是按照Android系统服务的模式进行部署，系统服务的部分数据也是data/system下，是符合逻辑的。

**Comment by txw-yates** [comment]
> [thanox_2.1-4-f795802-prc.apk.zip](https://github.com/Tornaco/Thanox/files/5589685/thanox_2.1-4-f795802-prc.apk.zip)
> 
> 辛苦试试这个版本~

神速👍， 我来试一下

**Comment by Tornaco** [comment]
@txw-yates haode，如果问题还存在请反馈~

**Comment by txw-yates** [comment]
> @txw-yates haode，如果问题还存在请反馈~

好像没啥问题了，昨天晚上用到现在，没有发生过重启

**Comment by Tornaco** [comment]
@txw-yates Thanks
