### ISSUE TITLE
thanox不能正常运行

### ISSUE THREAD

**Issue by ajdgsu** [Tornaco/Thanox#288]
**Describe the bug（现象描述）**
A clear and concise description of what the bug is.（简洁的描述该bug的现象）
激活后会不停报错(大概一秒十几次同样的报错)，手机可以正常运行，但是打开相机后手机过一会就会卡死重启
**To Reproduce**（如何复现）
激活就会复现
Steps to reproduce the behavior:（复现步骤）
激活就会复现
**Expected behavior**（期望结果）
正常运行

**Screenshots**（截图）
![Screenshot_20210725-000110_LSPosed](https://user-images.githubusercontent.com/45306865/126874203-2d5255ed-a981-4b92-9292-cecd2eddf5d9.jpg)

**Version（发现问题的版本）:**
 - OS: [Android 11]
 - Version [ v2.3.4 & v2.3.5]

**Additional context**（其他信息）
我怀疑是手机内核的问题，它貌似无法关闭selinux
感觉激活后手机的缓存出现了一定问题，例如剪贴板不能正常工作，打开相机手机就会卡死重启，有时候设备无法创建或删除文件(提示存储空间已满(虽然并没有))，有时候震动反馈不能正确触发等

手机是三星s20+，使用的lsposed1.4.7激活，使用官方内核和官改内核(jimbok_kernel)(官改内核源码在此https://github.com/Jimbo77/Jimbok_common_sm8250-R )测试后均无效

我曾经在android10的时候使用过thanox是没有任何报错的，应该是android11或者是新内核的问题(我在android10版本中成功关闭过selinux)

顺便一提目前有没有办法彻底移除selinux(或者说阻止selinux在启动时加载)而不是关闭selinux的方法?我想尝试下这样是否可行

** Logs**（日志文件）
2021-07-24 16:04:17.017 E/android(1164-6944): java.lang.SecurityException: resolveContentProvider: Requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS.
	at com.android.server.pm.permission.PermissionManagerService.enforceCrossUserPermission(PermissionManagerService.java:5350)
	at com.android.server.pm.permission.PermissionManagerService.access$2200(PermissionManagerService.java:222)
	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.enforceCrossUserPermission(PermissionManagerService.java:5705)
	at com.android.server.pm.PackageManagerService.resolveContentProviderInternal(PackageManagerService.java:10716)
	at com.android.server.pm.PackageManagerService.resolveContentProvider(PackageManagerService.java:10697)
	at android.app.ApplicationPackageManager.resolveContentProviderAsUser(ApplicationPackageManager.java:1558)
	at android.app.ApplicationPackageManager.resolveContentProvider(ApplicationPackageManager.java:1551)
	at github.tornaco.android.thanos.services.app.ActivityManagerService.checkContentProvider(Unknown Source:25)
	at github.tornaco.android.thanos.services.xposed.hooks.q.core.AMSGetProviderImplRegistry$1.beforeHookedMethod(Unknown Source:20)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.getContentProvider(Unknown Source:31)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2840)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3628)
	at android.os.Binder.execTransactInternal(Binder.java:1190)
	at android.os.Binder.execTransact(Binder.java:1159)

(所有报错日志全部一致)

**Comment by ajdgsu** [comment]
最新版(3.0alpha)已得到解决
