### ISSUE TITLE
MIUI11 Android 9无法激活

### ISSUE THREAD

**Issue by jw8013** [Tornaco/Thanox#310]
**Describe the bug**
无法激活

**To Reproduce**
卸载重新安装都没用！

**Expected behavior**
修复不能激活的问题

**Screenshots**
![Screenshot_2021-08-29-18-46-48-679_github tornaco android thanos pro](https://user-images.githubusercontent.com/10069562/131247734-d8e1b69b-7527-467e-a149-20f4f4c3561b.png)

**Version（发现问题的版本）:**
 - OS: Android 9 MIUI11
 - Version3.0

** Logs**（日志文件）
[LSPosed-2021-08-29.zip](https://github.com/Tornaco/Thanox/files/7072291/LSPosed-2021-08-29.zip)

**Comment by Tornaco** [comment]
Mark.

```java
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/accessibilityservice/IAccessibilityServiceClient$Default;
	at f.a.b.a.a.c(Unknown Source:11913)
	at f.a.b.a.a.<clinit>(Unknown Source:168)
	... 15 more
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/accessibilityservice/IAccessibilityServiceClient$Default;
	at dalvik.system.DexFile.defineClassNative(Native Method)
	at dalvik.system.DexFile.defineClass(DexFile.java:287)
	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:280)
	at dalvik.system.DexPathList$Element.findClass(DexPathList.java:752)
	at dalvik.system.DexPathList.findClass(DexPathList.java:499)
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:169)
	at s1.loadClass(Unknown Source:18)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at github.tornaco.android.thanos.services.ThanosService.<init>(Unknown Source:87)
	at github.tornaco.android.thanos.services.BootStrap.<clinit>(Unknown Source:35)
	at github.tornaco.android.thanos.services.xposed.hooks.privacy.OpsServiceRegistry.<init>(Unknown Source:3)
	at f.a.b.a.a.c(Unknown Source:1290)
	... 16 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.accessibilityservice.IAccessibilityServiceClient$Default" on path: DexPathList[[dex file "InMemoryDexFile[cookie=[0, 510160217856]]", dex file "InMemoryDexFile[cookie=[0, 510160218240]]"],nativeLibraryDirectories=[/system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
	at s1.loadClass(Unknown Source:18)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Comment by jw8013** [comment]
> Mark.
> 
> ```java
> Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/accessibilityservice/IAccessibilityServiceClient$Default;
> 	at f.a.b.a.a.c(Unknown Source:11913)
> 	at f.a.b.a.a.<clinit>(Unknown Source:168)
> 	... 15 more
> Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/accessibilityservice/IAccessibilityServiceClient$Default;
> 	at dalvik.system.DexFile.defineClassNative(Native Method)
> 	at dalvik.system.DexFile.defineClass(DexFile.java:287)
> 	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:280)
> 	at dalvik.system.DexPathList$Element.findClass(DexPathList.java:752)
> 	at dalvik.system.DexPathList.findClass(DexPathList.java:499)
> 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:169)
> 	at s1.loadClass(Unknown Source:18)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> 	at github.tornaco.android.thanos.services.ThanosService.<init>(Unknown Source:87)
> 	at github.tornaco.android.thanos.services.BootStrap.<clinit>(Unknown Source:35)
> 	at github.tornaco.android.thanos.services.xposed.hooks.privacy.OpsServiceRegistry.<init>(Unknown Source:3)
> 	at f.a.b.a.a.c(Unknown Source:1290)
> 	... 16 more
> Caused by: java.lang.ClassNotFoundException: Didn't find class "android.accessibilityservice.IAccessibilityServiceClient$Default" on path: DexPathList[[dex file "InMemoryDexFile[cookie=[0, 510160217856]]", dex file "InMemoryDexFile[cookie=[0, 510160218240]]"],nativeLibraryDirectories=[/system/lib64, /system/vendor/lib64]]
> 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
> 	at s1.loadClass(Unknown Source:18)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> ```

[LSPosed_2021-09-05T.zip](https://github.com/Tornaco/Thanox/files/7110751/LSPosed_2021-09-05T.zip)
Cannot load module: github.tornaco.android.thanos.pro

**Comment by Tornaco** [comment]
How about 3.0-alpha05-row? Released a moment ago.

**Comment by jw8013** [comment]
> How about 3.0-alpha05-row? Released a moment ago.

这个版本正常了。
