### ISSUE TITLE
无法激活

### ISSUE THREAD

**Issue by weGHub** [Tornaco/Thanox#312]
这个是lsp的日志：
Model: MI 6
Fingerprint: Xiaomi/sagit/sagit:7.1.1/NMF26X/V8.2.17.0.NCACNEC:user/release-keys
ROM description: sagit-user 7.1.1 NMF26X V8.2.17.0.NCACNEC release-keys
Architecture: arm64-v8a
Android build: 10
Android version: 10
Android sdk: 29
LSPosed version: v1.4.8 (5878)
Riru version: v26.0.5.r484.a8c93a12f8 (484)
Riru api: 26
Magisk: 7717f0a6-lite (23001)
1971-10-06 04:27:49.049 I/android(1381-1381): hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@18a1f23]
1971-10-06 04:27:50.050 E/android(1381-1381): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/server/pm/parsing/pkg/AndroidPackage;
	at java.lang.reflect.Executable.getParameterTypesInternal(Native Method)
	at java.lang.reflect.Method.getParameterTypes(Method.java:186)
	at java.lang.Class.getDeclaredMethods(Class.java:1884)
	at de.robv.android.xposed.XposedBridge.hookAllMethods(Unknown Source:5)
	at github.tornaco.android.thanos.services.xposed.hooks.pm.SetApplicationEnabledSettingRegistry.hookPackageManagerServiceAppSetting(Unknown Source:20)
	at github.tornaco.android.thanos.services.xposed.hooks.pm.SetApplicationEnabledSettingRegistry.handleLoadPackage(Unknown Source:12)
	at github.tornaco.android.thanos.services.xposed.XposedHookEntry.handleLoadPackage(Unknown Source:62)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:28)
	at Q0.beforeHookedMethod(:1)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.startBootstrapServices(Unknown Source:8)
	at com.android.server.SystemServer.run(Unknown Source:317)
	at com.android.server.SystemServer.main(Unknown Source:10)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:251)
Caused by: java.lang.ClassNotFoundException: com.android.server.pm.parsing.pkg.AndroidPackage
	... 18 more

2018-12-31 16:00:00.000 I/android(2344-2344): hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@cd61052]
2018-12-31 16:00:01.001 I/android(2630-2630): hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@cd61052]
2018-12-31 16:00:01.001 I/android(2662-2662): hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@cd61052]

**Comment by Tornaco** [comment]
@weGHub 请提供完整日志，看日志片段只能初步判断是xp框架的hookMethod过程出错。

**Comment by Tornaco** [comment]
Close since no log provided.
