### ISSUE TITLE
NFC服务无限FC

### ISSUE THREAD

**Issue by qiuyouxin** [Tornaco/Thanox#315]
①BUG：NFC服务不断FC

②现象：梦境框架，激活重启后显示正常激活，但NFC服务一直弹窗FC。由于此现象全部功能暂未开启使用。

③希望作者能抽空查看并消灭此虫。由于lsp不支持安卓8.0，edxposed停止更新未适配riru25+，所以转入梦境框架，希望能适配 
   下梦境框架。如是梦境框架问题，望大佬能联系下梦境作者，我们去联系估计理都不会理我们尴尬。
   
   （想问下作者：riru模块激活能否实现安卓8.0以上系统激活，哪怕简单的管理自启，划卡强退功能就行。因为注入xposed就会被检测到， 所以希望能通过riru-core实现。如果实现太困难，请无视此请求。）

④**Version（发现问题的版本）:**
 - OS: LG，安卓8.0.0
 - Version ：正在测试版本v3.0-alpha04-2。能激活thanos历史版本都有这问题，包括旧版 “应用管理xposed”。
 - 作用域只添加了：安卓系统，thanos本身。

⑤按要求提取相关目录logs，如需其他请说。

[thanos_logs.zip](https://github.com/Tornaco/Thanox/files/7112110/thanos_logs.zip)

**Comment by Tornaco** [comment]
@qiuyouxin Magisk模式适配成本高，8.0暂时不支持了。个人经历只能维护Android 10以后的版本。

你描述的问题我看下日志，不确定是否能找到原因，如果能找到原因我会继续回复。

**Comment by Tornaco** [comment]
日志里看起来是nfc服务app的权限问题，具体为什么系统校验权限会失败，不得而知~

```
java.lang.RuntimeException: Unable to create application com.android.nfc.NfcApplication: java.lang.SecurityException: Permission Denial: broadcastIntent() requesting a sticky broadcast from pid=3457, uid=1027 requires android.permission.BROADCAST_STICKY
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5934)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1680)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
Caused by: java.lang.SecurityException: Permission Denial: broadcastIntent() requesting a sticky broadcast from pid=3457, uid=1027 requires android.permission.BROADCAST_STICKY
	at android.os.Parcel.readException(Parcel.java:1951)
	at android.os.Parcel.readException(Parcel.java:1897)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntent(IActivityManager.java:4704)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1118)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:499)
	at com.android.nfc.utils.LNfcCommon.sendNfcLdbIntent(LNfcCommon.java:376)
	at com.android.nfc.cardemulation.LCardEmulationManager.onPreferredPaymentServiceChanged(LCardEmulationManager.java:676)
	at com.android.nfc.cardemulation.PreferredServices.loadDefaultsFromSettings(PreferredServices.java:183)
	at com.android.nfc.cardemulation.PreferredServices.<init>(PreferredServices.java:123)
	at com.android.nfc.cardemulation.LPreferredServices.<init>(LPreferredServices.java:43)
	at com.android.nfc.cardemulation.VCardEmulationManager.<init>(VCardEmulationManager.java:47)
	at com.android.nfc.VNfcService.<init>(VNfcService.java:301)
	at com.android.nfc.NfcApplication.onCreate(NfcApplication.java:78)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5931)
	... 8 more

```

**Comment by qiuyouxin** [comment]
@Tornaco Android8.0能用的edxposed和lsp框架都没有这个问题，唯独是梦境框架才有这个问题，但ed不更新，lsp不支持8.0。如需进一步解决问题，请告知我应该如何配合。
[boot.log](https://github.com/Tornaco/Thanox/files/7232077/boot.log)
激活后boot.log
