### ISSUE TITLE
微信代收插件卡死闪退

### ISSUE THREAD

**Issue by dqwfgzs** [Tornaco/Thanox#320]
**Describe the bug（现象描述）**
安装好代收插件后点击它即闪退

**To Reproduce**（如何复现）
正常安装插件、勾选启用后重启

**Expected behavior**（期望结果）

**Screenshots**（截图）
![Screenshot_20210918-093111](https://user-images.githubusercontent.com/34101212/133867765-3476a2f9-3214-45e2-a344-a04e6fd52a45.png)
![Screenshot_20210918-093115](https://user-images.githubusercontent.com/34101212/133867770-f5f4bb89-6555-4bad-a576-5d3142b5caf3.png)

**Version（发现问题的版本）:**
 - OS: Android 9 47.2.A.11.228
 - 软件版本：2.5-9-2e3e319-pro-release-row

** Logs**（日志文件）
java.lang.RuntimeException: Unable to start activity ComponentInfo{github.tornaco.android.thanos.pro/github.tornaco.android.nitro.framework.host.ContainerActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void util.Consumer.accept(java.lang.Object)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2919)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3054)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at com.osama.firecrasher.e.run(Unknown Source:87)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:280)
	at android.app.ActivityThread.main(ActivityThread.java:6706)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void util.Consumer.accept(java.lang.Object)' on a null object reference
	at github.tornaco.android.thanos.core.app.ThanosManager.ifServiceInstalled(Unknown Source:6)
	at github.tornaco.android.thanos.theme.AppThemePreferences.getTheme(:36)
	at github.tornaco.android.thanos.theme.ThemeActivity.getAppTheme(:43)
	at github.tornaco.android.thanos.theme.ThemeActivity.onCreate(:31)
	at github.tornaco.android.plugin.push.message.delegate.MainActivity.onCreate(:18)
	at java.lang.reflect.Method.invoke(Native Method)
	at util.ReflectionUtils.invokeMethod(Unknown Source:4)
	at github.tornaco.android.nitro.framework.plugin.wrapper.PluginActivityWrapper.onCreate(Unknown Source:26)
	at github.tornaco.android.nitro.framework.plugin.PluginActivityInvoker.onCreate(Unknown Source:2)
	at github.tornaco.android.nitro.framework.host.ContainerActivity.onCreate(Unknown Source:72)
	at android.app.Activity.performCreate(Activity.java:7136)
	at android.app.Activity.performCreate(Activity.java:7127)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899)
	... 14 more

**Comment by dqwfgzs** [comment]
已经可以使用但无法激活，详见#328

**Comment by Tornaco** [comment]
Close. Track with #328
