### ISSUE TITLE
[Android 12] 系统死机重启

### ISSUE THREAD

**Issue by huyuxin95** [Tornaco/Thanox#346]
```
java.lang.IllegalArgumentException: android: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
at github.tornaco.android.thanos.services.app.ActivityManagerService.maybeShowBgRestrictNotification(Unknown Source:84)
at github.tornaco.android.thanos.services.app.ActivityManagerService.g(Unknown Source:0)
at kb.e.run(Unknown Source:8)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:210)
at android.os.Looper.loop(Looper.java:299)
at android.os.HandlerThread.run(HandlerThread.java:67)
```

麻烦根据开发者文档提示适配Android 12，多谢

https://developer.android.google.cn/about/versions/12/behavior-changes-12?hl=zh-cn#pending-intent-mutability

**Comment by Tornaco** [comment]
@huyuxin95 👍

**Comment by Tornaco** [comment]
https://github.com/Tornaco/Thanox/releases/tag/v3.0-beta3 @huyuxin95

**Comment by Tornaco** [comment]
Close since fixed.

**Comment by huyuxin95** [comment]
这是来自邮箱的自动回复邮件。
 
您好，我已收到你的发送的邮件，我将会尽快给您回复。
