### ISSUE TITLE
[Android12 v3.0-beat3]系统无故死机重启

### ISSUE THREAD

**Issue by a1342966673** [Tornaco/Thanox#352]
系统无故重启，目前发现的几次重启现象均为关屏状态时触发，不知如何复现
查Lsposed日志，锁定到重启时间得知thanox代码报错
其中一次重启时日志如下

`[ 2021-11-02T23:32:55.023     1000: 12194: 12237 E/LSPosed-Bridge  ] java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
	at github.tornaco.android.thanos.services.xposed.hooks.q.ops.OpsServiceRegistryQ$2.beforeHookedMethod(Unknown Source:42)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.noteProxyOperation(Unknown Source:42)
	at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:627)
	at android.os.Binder.execTransactInternal(Binder.java:1179)
	at android.os.Binder.execTransact(Binder.java:1143)
[ 2021-11-02T23:32:55.026     1000: 12194: 14346 E/LSPosed-Bridge  ] java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
	at github.tornaco.android.thanos.services.xposed.hooks.q.ops.OpsServiceRegistryQ$2.beforeHookedMethod(Unknown Source:42)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.noteProxyOperation(Unknown Source:42)
	at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:627)
	at android.os.Binder.execTransactInternal(Binder.java:1179)
	at android.os.Binder.execTransact(Binder.java:1143)`

日志文件中还有多次thanox出错的日志，由于忘记具体出问题的时间所以无法断定是否与死机重启有关，还是附上整个**日志文件**，开发者自行判断一下吧(；´д｀)ゞ

[modules_2021-11-02T18_41_38.984.txt](https://github.com/Tornaco/Thanox/files/7462184/modules_2021-11-02T18_41_38.984.txt)
~

**Comment by Tornaco** [comment]
[thanox_3.0-beta3-22-2d26360-prc(3060137).apk.zip](https://github.com/Tornaco/Thanox/files/7467544/thanox_3.0-beta3-22-2d26360-prc.3060137.apk.zip)

@a1342966673 试试这个版本，自测现在没有报这个错误了。

**Comment by a1342966673** [comment]
> [thanox_3.0-beta3-22-2d26360-prc(3060137).apk.zip](https://github.com/Tornaco/Thanox/files/7467544/thanox_3.0-beta3-22-2d26360-prc.3060137.apk.zip)
> 
> @a1342966673这个版本，自测现在没有报这个错误了。

安装到目前暂未发现设备重启现象，可认定问题已解决(′▽`〃)
