### ISSUE TITLE
点击插件卡死

### ISSUE THREAD

**Issue by AkinoKaede** [Tornaco/Thanox#45]
**Describe the bug（现象描述）**
A clear and concise description of what the bug is.（简洁的描述该bug的现象）
安装插件重启后，点击插件 Thanox卡死. 
**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 安装消息代收,并启用. 
2. 重启手机
3. 点击消息代收. 

**Expected behavior**（期望结果）
A clear and concise description of what you expected to happen.（描述一下期望的结果）

**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）

**Version（发现问题的版本）:**
 - OS: Android 10（系统版本，例如Android 6.0.1）
 - Version : 1.1.2_beta1（软件版本，例如v2.3.4）

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）
使用EdXposed 4497 SandHook（同时YAHFA也有相同问题)
** Logs**（日志文件）
https://del.dog/prufihingu.txt
thanox-core.log: https://del.dog/pulapolyfe.txt

**Comment by AkinoKaede** [comment]
补充日志 https://del.dog/utestipayf.txt

**Comment by Tornaco** [comment]
先Mark一下关键错误

```
ava.lang.ClassNotFoundException: Didn't find class "github.tornaco.android.nitro.framework.plugin.ComponentFactory" on path: DexPathList[[zip file "/data/app/github.tornaco.android.thanos-aAPmN9qBe-drsSm_1fLF_w==/base.apk"],nativeLibraryDirectories=[/data/app/github.tornaco.android.thanos-aAPmN9qBe-drsSm_1fLF_w==/lib/arm64, /system/lib64, /system/product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at github.tornaco.android.nitro.framework.plugin.PluginClassLoader.loadClassInternal(Unknown Source:16)
	at github.tornaco.android.nitro.framework.plugin.PluginClassLoader.loadClass(Unknown Source:0)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at github.tornaco.android.nitro.framework.host.Launcher.loadPluginActivityInstance(Unknown Source:88)
	at github.tornaco.android.nitro.framework.host.ContainerActivity.onCreate(Unknown Source:6)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at com.osama.firecrasher.e.run(Unknown Source:87)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:920)
```

**Comment by AkinoKaede** [comment]
问题解决，感谢

**Comment by anysoft** [comment]
> 先Mark一下关键错误
> 
> ```
> ava.lang.ClassNotFoundException: Didn't find class "github.tornaco.android.nitro.framework.plugin.ComponentFactory" on path: DexPathList[[zip file "/data/app/github.tornaco.android.thanos-aAPmN9qBe-drsSm_1fLF_w==/base.apk"],nativeLibraryDirectories=[/data/app/github.tornaco.android.thanos-aAPmN9qBe-drsSm_1fLF_w==/lib/arm64, /system/lib64, /system/product/lib64]]
> 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> 	at github.tornaco.android.nitro.framework.plugin.PluginClassLoader.loadClassInternal(Unknown Source:16)
> 	at github.tornaco.android.nitro.framework.plugin.PluginClassLoader.loadClass(Unknown Source:0)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> 	at github.tornaco.android.nitro.framework.host.Launcher.loadPluginActivityInstance(Unknown Source:88)
> 	at github.tornaco.android.nitro.framework.host.ContainerActivity.onCreate(Unknown Source:6)
> 	at android.app.Activity.performCreate(Activity.java:7824)
> 	at android.app.Activity.performCreate(Activity.java:7813)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
> 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
> 	at android.os.Handler.dispatchMessage(Handler.java:107)
> 	at com.osama.firecrasher.e.run(Unknown Source:87)
> 	at android.os.Handler.handleCallback(Handler.java:883)
> 	at android.os.Handler.dispatchMessage(Handler.java:100)
> 	at android.os.Looper.loop(Looper.java:214)
> 	at android.app.ActivityThread.main(ActivityThread.java:7397)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:920)
> ```

你好，这个bug在thanox 2.0+ 上复现，我退回1.3.2版本正常。升级2.0之后点击消息代收插件thanox就闪退，之前看日志和上述一样都是找不到class
