### ISSUE TITLE
Thanox pro 3.9和3.9.3谷歌商店版 与安卓12系统界面有冲突

### ISSUE THREAD

**Issue by RoyZ-iwnl** [Tornaco/Thanox#454]
**Describe the bug（现象描述）**
A clear and concise description of what the bug is.（简洁的描述该bug的现象）
与Crdroid ROM的系统启动器有冲突，无法使用整个CRDROID系统界面
另外权限管理怎么更新更没了
**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
谷歌商店thanox pro付费版本 3.9和beta3.9.3

**Expected behavior**（期望结果）
A clear and concise description of what you expected to happen.（描述一下期望的结果）

**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题

没啥，系统界面直接停止运行

**Version（发现问题的版本）:**
 - OS: 安卓12
 - Version 3.9和3.9.3

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）
机型国行一加8pro 刷的[Crdroid 8.3](https://crdroid.net/instantnoodlep/8) 
** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。
```
time: 1649008460177
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'com.android.server.wm.TaskFragment com.android.server.wm.Task.getAdjacentTaskFragment()' on a null object reference
stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'com.android.server.wm.TaskFragment com.android.server.wm.Task.getAdjacentTaskFragment()' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2431)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at android.app.IActivityTaskManager$Stub$Proxy.getTasks(IActivityTaskManager.java:3053)
	at java.lang.reflect.Method.invoke(Native Method)
	at x.b.tryInvoke(ExceptionTransformedInvocationHandler.java:1)
	at github.tornaco.android.thanox.magisk.bridge.proxy.am.ActivityTaskManagerProxyProvider.tryInvoke(Unknown Source:0)
	at github.tornaco.android.thanox.magisk.bridge.proxy.am.ActivityTaskManagerProxyProvider$1.lambda$onQueryLocalInterface$0(ActivityTaskManagerProxyProvider.java:10)
	at github.tornaco.android.thanox.magisk.bridge.proxy.am.ActivityTaskManagerProxyProvider$1.a(Unknown Source:0)
	at github.tornaco.android.thanox.magisk.bridge.proxy.am.a.b(Unknown Source:8)
	at github.tornaco.android.thanox.magisk.bridge.proxy.am.a.invoke(Unknown Source:10)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy4.getTasks(Unknown Source)
	at android.app.ActivityTaskManager.getTasks(ActivityTaskManager.java:400)
	at android.app.ActivityTaskManager.getTasks(ActivityTaskManager.java:389)
	at com.android.systemui.shared.system.ActivityManagerWrapper.getRunningTasks(ActivityManagerWrapper.java:127)
	at com.android.quickstep.TouchInteractionService.lambda$createGestureState$1$TouchInteractionService(TouchInteractionService.java:679)
	at com.android.quickstep.TouchInteractionService$$ExternalSyntheticLambda10.get(Unknown Source:2)
	at com.android.launcher3.util.TraceHelper.allowIpcs(TraceHelper.java:84)
	at com.android.quickstep.TouchInteractionService.createGestureState(TouchInteractionService.java:678)
	at com.android.quickstep.TouchInteractionService.onInputEvent(TouchInteractionService.java:595)
	at com.android.quickstep.TouchInteractionService.$r8$lambda$QnySfMPM3HQvC_OREg1W70p37mY(Unknown Source:0)
	at com.android.quickstep.TouchInteractionService$$ExternalSyntheticLambda4.onInputEvent(Unknown Source:2)
	at com.android.systemui.shared.system.InputChannelCompat$InputEventReceiver$1.onInputEvent(InputChannelCompat.java:74)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:161)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
GitHub
```

**Comment by RoyZ-iwnl** [comment]
另激活方式为zygisk，经调试使用LSPosed 激活没有问题

**Comment by Tornaco** [comment]
@RoyZ-CSGO 建议先用lsp激活，我会尝试复现修复这个问题，但是不确定什么时候能解决哦。

**Comment by Jieoz** [comment]
中奖了
