### ISSUE TITLE
红米K40pro无法安装su插件

### ISSUE THREAD

**Issue by Wcoom** [Tornaco/Thanox#488]
使用6519版zygisk的lsposed激活  安卓12
thanox的插件仓库su插件无法安装和本地安装，格式化data再次安装依旧无法安装和安装
Thanox-Core: BootStrap main: Xposed
Thanox-Core: registerFeature: thanox.feature.start.blocker
Thanox-Core: registerFeature: thanox.feature.privacy.data.cheat
Thanox-Core: registerFeature: thanox.feature.plugin.support
Thanox-Core: registerFeature: thanox.feature.privacy.field.imei
Thanox-Core: registerFeature: thanox.feature.ext.n.up
Thanox-Core: registerFeature: thanox.feature.dialog.force.cancelable
Thanox-Core: registerFeature: thanox.feature.privacy.field.meid
Thanox-Core: registerFeature: thanox.feature.privacy.ops.reminder
Thanox-Core: registerFeature: thanox.feature.app.trampoline
Thanox-Core: registerFeature: thanox.feature.prevent.uninstall
Thanox-Core: registerFeature: thanox.feature.privacy.task.blur
Thanox-Core: registerFeature: thanox.feature.recent.force.exclude
Thanox-Core: registerFeature: thanox.feature.push.delegate
Thanox-Core: registerFeature: thanox.feature.ext.app.smart.freeze
Thanox-Core: registerFeature: thanox.feature.prevent.clear.data
Thanox-Core: registerFeature: thanox.feature.profile
Thanox-Core: registerFeature: thanox.feature.profile.accessibility
Thanox-Core: registerFeature: thanox.feature.app.smart_standby
Thanox-Core: registerFeature: thanox.feature.recent.task.removal
Thanox-Core: registerFeature: thanox.feature.recent.force.include
Thanox-Core: registerFeature: thanox.feature.privacy.ops
Thanox-Core: registerFeature: thanox.feature.app.smart_service_stopper
Thanox-Core: registerFeature: thanox.feature.background.task.clean
Thanox-Core: registerFeature: thanox.feature.privacy.applock
Thanox-Core: registerFeature: thanox.feature.component.manager
Thanox-Core: registerFeature: thanox.feature.ext.n.recorder
Thanox-Core: Bring up with thanos: github.tornaco.android.thanos.services.ThanosService@40c0521, sdk: 31
Thanox-Core: Invoke handleLoadPackage: github.tornaco.android.thanos.services.xposed.hooks.pm.SetApplicationEnabledSettingRegistry@b346d46
Thanox-Core: hookPackageManagerServiceAppSetting...
Thanox-Core: hookPackageManagerServiceAppSetting OK:[de.robv.android.xposed.XC_MethodHook$Unhook@8c20b07]
Thanox-Core: Invoke handleLoadPackage: github.tornaco.android.thanos.services.xposed.hooks.pm.SetComponentEnabledSettingRegistry@8650434
Thanox-Core: hookPackageManagerServiceCompSetting...
Thanox-Core: hookPackageManagerServiceCompSetting OK:[de.robv.android.xposed.XC_MethodHook$Unhook@e82d25d]
Thanox-Core: Invoke handleLoadPackage: github.tornaco.android.thanos.services.xposed.hooks.pm.PackageManagerServiceRegistry@aba17d2
Thanox-Core: hookPackageManagerServiceInit...
Thanox-Core: hookPackageManagerServiceInit OK: [de.robv.android.xposed.XC_MethodHook$Unhook@3682fa0, de.robv.android.xposed.XC_MethodHook$Unhook@2ea50a3]
Thanox-Core: hookPackageManagerServiceSystemReady...
Thanox-Core: hookPackageManagerServiceSystemReady OK: [de.robv.android.xposed.XC_MethodHook$Unhook@79f3759]
Thanox-Core: hookClearApplicationUserData...
Thanox-Core: hookClearApplicationUserData OK:[de.robv.android.xposed.XC_MethodHook$Unhook@97ddf1e]
Thanox-Core: hookPackageManagerServiceSetAppEnabled...
Thanox-Core: hookPackageManagerServiceSetAppEnabled OK: [de.robv.android.xposed.XC_MethodHook$Unhook@3c753ff]
Thanox-Core: Invoke handleLoadPackage: github.tornaco.android.thanos.services.xposed.hooks.pm.PackageInstallerRegistry@db0a5cc
Thanox-Core: hookPackageInstaller.
Thanox-Core: hookPackageInstaller OK:[de.robv.android.xposed.XC_MethodHook$Unhook@e82f015]
Thanox-Core: hookDeletePkgX.
Thanox-Core: hookDeletePkgX OK:[de.robv.android.xposed.XC_MethodHook$Unhook@824cf2a]
Thanox-Core: Invoke handleLoadPackage: github.tornaco.android.thanos.services.xposed.hooks.power.PowerManagerServiceRegistry@347311b
Thanox-Core: hookNotifyWakeLockAcquired, unhooks [de.robv.android.xposed.XC_MethodHook$Unhook@c2852b8]
Thanox-Core: notifyWakeLockReleasedLocked, unhooks [de.robv.android.xposed.XC_MethodHook$Unhook@8af7891]
Thanox-Core: Invoke handleLoadPackage: github.tornaco.android.thanos.services.xposed.hooks.workaround.NetworkStatsServiceFixRegistry@a98b3f6
Thanox-Core: hookAdvisePersistThreshold, unhooks [de.robv.android.xposed.XC_MethodHook$Unhook@1dc3f7]
Thanox-Core: Invoke handleLoadPackage: github.tornaco.android.thanos.services.xposed.hooks.workaround.ActiveServicesBindingFixRegistry@66be264
Thanox-Core: bindServiceLocked, unhooks [de.robv.android.xposed.XC_MethodHook$Unhook@8420ccd]
Thanox-Core: hookStartService, unhooks [de.robv.android.xposed.XC_MethodHook$Unhook@660a893, de.robv.android.xposed.XC_MethodHook$Unhook@7941982]
Thanox-Core: Invoke handleLoadPackage: github.tornaco.android.thanos.services.xposed.hooks.privacy.TelephonyManagerRegister@f36c0d0
Thanox-Core: Invoke handleLoadPackage: github.tornaco.android.thanos.services.xposed.hooks.privacy.SecureSettingsRegistry@9efa8c9
Thanox-Core: Invoke handleLoadPackage: github.tornaco.android.thanos.services.xposed.hooks.privacy.PMSGetPackageInfoRegistry@4ee4bce
Thanox-Core: hookGetPackageInfo...
Thanox-Core: hookGetInstalledPkgs OK:[de.robv.android.xposed.XC_M

**Comment by Wcoom** [comment]
2022-05-07 13:34:01.119 W/Thanox-Core: SystemServiceLifecycle onStart: [github.tornaco.android.thanos.services.os.UserManagerService@6ab86c1, github.tornaco.android.thanos.services.app.ActivityManagerService@45d5e66, github.tornaco.android.thanos.services.os.ServiceManagerService@76875a7, github.tornaco.android.thanos.services.pm.PkgManagerService@17d2a54, github.tornaco.android.thanos.services.pm.AppComponentService@628cdfd, github.tornaco.android.thanos.services.perf.PreferenceManagerService@cd0faf2, github.tornaco.android.thanos.services.perf.SecureSettingsService@a9cc543, github.tornaco.android.thanos.services.app.ActivityStackSupervisorService@dac97c0, github.tornaco.android.thanos.services.secure.PrivacyService@7394cf9, github.tornaco.android.thanos.services.secure.ops.AppOpsService@a6fd43e, github.tornaco.android.thanos.services.push.PushManagerService@a3c729f, github.tornaco.android.thanos.services.n.NotificationManagerService@ca36fec, github.tornaco.android.thanos.services.audio.AudioService@a38bfb5, github.tornaco.android.thanos.services.backup.BackupAgentService@f90f64a, github.tornaco.android.thanos.services.wm.WindowManagerService@2ff99bb, github.tornaco.android.thanos.services.profile.ProfileService@94d9ed8, github.tornaco.android.thanos.services.power.PowerService@f82a231, github.tornaco.android.thanos.services.input.InputManagerService@af02d16, github.tornaco.android.thanos.services.app.infinite.InfiniteZService@b041697, github.tornaco.android.thanos.services.app.usage.UsageStatsService@f69d084, github.tornaco.android.thanos.services.push.wechat.PushDelegateService@7ae306d, github.tornaco.android.thanos.services.v.RSS@93a04a2]
2022-05-07 13:34:01.129 W/Thanox-Core: getBaseFile not exists, skip load: recent_task_blur_pkgs
2022-05-07 13:34:01.130 W/Thanox-Core: getBaseFile not exists, skip load: start_rules
2022-05-07 13:34:01.219 W/Thanox-Core: getBaseFile not exists, skip load: block_clear_data_pkgs
2022-05-07 13:34:01.219 W/Thanox-Core: getBaseFile not exists, skip load: block_uninstall_pkgs
2022-05-07 13:34:01.220 W/Thanox-Core: getBaseFile not exists, skip load: pkg_sets
2022-05-07 13:34:01.229 W/Thanox-Core: getBaseFile not exists, skip load: component_replacements
2022-05-07 13:34:01.230 W/Thanox-Core: getBaseFile not exists, skip load: priv_pkg_fields
2022-05-07 13:34:01.231 W/Thanox-Core: getAllFieldsProfilesFromFile, parse: /data/system/thanos_cWvoqIufYRjTrdBz/data/u/0/priv_fields, out: null
2022-05-07 13:34:01.231 W/Thanox-Core: getBaseFile not exists, skip load: reminding_ops
2022-05-07 13:34:01.231 W/Thanox-Core: getBaseFile not exists, skip load: op_reminding_pkgs
2022-05-07 13:34:01.253 W/Thanox-Core: getBaseFile not exists, skip load: dialog_cancelable_forced_pkgs
2022-05-07 13:34:01.255 W/Thanox-Core: ProfileService server handler: Handler (android.os.Handler) {c54822b}
2022-05-07 13:34:01.255 W/Thanox-Core: PushDelegateServer start with context: android.app.ContextImpl@e7127cb
2022-05-07 13:34:01.258 W/Thanox-Core: ThanosManagerNative, setLocalService: github.tornaco.android.thanos.services.ThanosServiceStub@7e6b688
2022-05-07 13:34:01.259 W/Thanox-Core: onAttachActivityManagerServiceProxy: ActiveServicesProxy{host=com.android.server.am.ActiveServices@e095821}
2022-05-07 13:34:01.259 W/Thanox-Core: onAttachActivityManagerServiceProxy: ActivityManagerServiceProxy{host=com.android.server.am.ActivityManagerService@974fadc}
2022-05-07 13:34:02.633 W/Thanox-Core: onPackageManagerServiceAttach: PackageManagerServiceProxy{host=com.android.server.pm.PackageManagerService@592bd5e}
2022-05-07 13:34:04.614 W/Thanox-Core: onPackageManagerServiceAttach: PackageManagerServiceProxy{host=com.android.server.pm.PackageManagerService@592bd5e}
2022-05-07 13:34:04.636 W/Thanox-Core: === hasTVFeature? FEATURES DUMP START ===
2022-05-07 13:34:04.636 W/Thanox-Core: android.hardware.sensor.proximity
2022-05-07 13:34:04.636 W/Thanox-Core: android.hardware.sensor.accelerometer
2022-05-07 13:34:04.636 W/Thanox-Core: android.software.controls
2022-05-07 13:34:04.636 W/Thanox-Core: android.hardware.faketouch
2022-05-07 13:34:04.636 W/Thanox-Core: android.hardware.usb.accessory
2022-05-07 13:34:04.636 W/Thanox-Core: android.hardware.telephony.cdma
2022-05-07 13:34:04.636 W/Thanox-Core: android.software.backup
2022-05-07 13:34:04.636 W/Thanox-Core: android.hardware.touchscreen
2022-05-07 13:34:04.636 W/Thanox-Core: android.hardware.touchscreen.multitouch
2022-05-07 13:34:04.636 W/Thanox-Core: android.software.print
2022-05-07 13:34:04.636 W/Thanox-Core: android.hardware.consumerir
2022-05-07 13:34:04.636 W/Thanox-Core: android.hardware.ethernet
2022-05-07 13:34:04.636 W/Thanox-Core: android.software.activities_on_secondary_displays
2022-05-07 13:34:04.636 W/Thanox-Core: android.hardware.wifi.rtt
2022-05-07 13:34:04.636 W/Thanox-Core: android.software.voice_recognizers
2022-05-07 13:34:04.636 W/Thanox-Core: android.software.picture_in_picture
2022-05-07 13:34:04.636 W/Thanox-Core: android.hardware.fingerprin

**Comment by Wcoom** [comment]
https://user-images.githubusercontent.com/105034279/167241507-b17424b5-2cd8-41e5-8232-9f7bbafb7619.mp4

点击安装后，无任何反馈，依旧在这个界面

**Comment by Wcoom** [comment]
rom是simplicity rom官改，MIUI13 22.4.27

**Comment by ICCID0211** [comment]
解决了吗兄弟，我也是这样的问题

**Comment by Tornaco** [comment]
等下个版本

**Comment by Tornaco** [comment]
@Wcoom 把你的日志也发一下。 sdcard/Android/data/github.tornaco...thanos/cache/log

**Comment by Wcoom** [comment]
> @Wcoomsdcard 链接:https://wwr.lanzoui.com/b031178gh  提取码 : gu51

**Comment by Wcoom** [comment]
> @Wcoomsdcard／Android／data／github．tornaco．．．thanos／cache／log

我用蓝奏浏览器分享了[thanox的log], 下载链接:https://wwr.lanzoui.com/b031178gh  提取码 : gu51, 你可以不限速下载哦

**Comment by Tornaco** [comment]
@Wcoom 除了个日志还有一个路径下面的日志：sdcard/Android/data/github.tornaco...thanos/cache/log

这个也发下。

**Comment by Wcoom** [comment]
> @Wcoom 除了个日志还有一个路径下面的日志：sdcard/Android/data/github.tornaco...thanos/cache/log
> 
> 这个也发下。

在sdcard/Android/data/github.tornaco...thanos/文件下没有产生任何文件

**Comment by Tornaco** [comment]
@Wcoom 用这个版本测试，出错了复制一下错误信息发出来。

https://app.circleci.com/pipelines/github/Tornaco/Thanox/304/workflows/d1d10d57-706e-45d4-a077-366175a46ded/jobs/282/artifacts

**Comment by Wcoom** [comment]
> @Wcoom 用这个版本测试，出错了复制一下错误信息发出来。
> 
> https://app.circleci.com/pipelines/github/Tornaco/Thanox/304/workflows/d1d10d57-706e-45d4-a077-366175a46ded/jobs/282/artifacts

没有错误信息提示，点击安装后和上面视频一样无任何反应错误提示又继续在仓库插件页面

**Comment by Tornaco** [comment]
/sdcard/Android/data/github.tornaco.android.thanos/cache/logs

再确认下这个路径下有没有日志？没有日志我也无法解决了。

**Comment by Tornaco** [comment]
再试试这个呢 https://app.circleci.com/pipelines/github/Tornaco/Thanox/305/workflows/4c7dcc4a-6515-4ee2-b764-9435ea0e565c/jobs/283/artifacts

**Comment by Wcoom** [comment]
> 再试试这个呢 https://app.circleci.com/pipelines/github/Tornaco/Thanox/305/workflows/4c7dcc4a-6515-4ee2-b764-9435ea0e565c/jobs/283/artifacts

有了 错误信息:
java.io.FileNotFoundException: plugin_tmp1653058762101.tp: open failed: EROFS (Read-only file system)
	at libcore.io.IoBridge.open(IoBridge.java:575)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
	at util.AssetUtils.copyTo(:5)
	at k3.a.run(:7)
	at github.tornaco.android.thanos.widget.e.onClick(:3)
	at androidx.appcompat.app.AlertController$c.handleMessage(Unknown Source:37)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1046)
Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8111)
	at libcore.io.IoBridge.open(IoBridge.java:561)
	... 12 more

**Comment by ICCID0211** [comment]
> 再试试这个呢 https://app.circleci.com/pipelines/github/Tornaco/Thanox/305/workflows/4c7dcc4a-6515-4ee2-b764-9435ea0e565c/jobs/283/artifacts

大佬你好，我跟他是一模一样的情况，k30pro 安卓12.1。
用的是你发的这个版本，这里是错误信息：
java.io.FileNotFoundException: plugin_tmp1653059930442.tp: open failed: EROFS (Read-only file system)
	at libcore.io.IoBridge.open(IoBridge.java:575)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
	at util.AssetUtils.copyTo(:5)
	at k3.a.run(:7)
	at github.tornaco.android.thanos.widget.e.onClick(:3)
	at androidx.appcompat.app.AlertController$c.handleMessage(Unknown Source:37)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7866)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7752)
	at libcore.io.IoBridge.open(IoBridge.java:561)
	... 12 more
![Screenshot_20220520-231857_Thanox.png](https://user-images.githubusercontent.com/84228301/169560035-e448b25f-48af-4bf9-9c86-0d07492dbe83.png)

**Comment by Tornaco** [comment]
@ICCID0211 @Wcoom 看错误是没权限写缓存，调整了一下缓存位置。等下面这个编译完了，可以测试下。

https://app.circleci.com/pipelines/github/Tornaco/Thanox/307/workflows/21ec4ad7-12f6-4a9c-9806-b3576618ff5b/jobs/285/artifacts

**Comment by Wcoom** [comment]
> @ICCID0211 @Wcoom 看错误是没权限写缓存，调整了一下缓存位置。等下面这个编译完了，可以测试下。
> 
> https://app.circleci.com/pipelines/github/Tornaco/Thanox/307/workflows/21ec4ad7-12f6-4a9c-9806-b3576618ff5b/jobs/285/artifacts

👌🏻

**Comment by Wcoom** [comment]
> @ICCID0211 @Wcoom 看错误是没权限写缓存，调整了一下缓存位置。等下面这个编译完了，可以测试下。
> 
> https://app.circleci.com/pipelines/github/Tornaco/Thanox/307/workflows/21ec4ad7-12f6-4a9c-9806-b3576618ff5b/jobs/285/artifacts

OK了，完美解决su插件安装成功，类似墓碑后太命令也能执行

**Comment by ICCID0211** [comment]
> @ICCID0211 @Wcoom 看错误是没权限写缓存，调整了一下缓存位置。等下面这个编译完了，可以测试下。
> 
> https://app.circleci.com/pipelines/github/Tornaco/Thanox/307/workflows/21ec4ad7-12f6-4a9c-9806-b3576618ff5b/jobs/285/artifacts

解决了！
