### ISSUE TITLE
Magisk版弹出指纹认证时软重启

### ISSUE THREAD

**Issue by Gluneklairo** [Tornaco/Thanox#615]
**Describe the bug（现象描述）**
Magisk版激活后，任何app将要弹出指纹认证界面时软重启

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 打开任何弹出指纹认证的界面如Telegram密码锁
2. 软重启

**Expected behavior**（期望结果）
正常弹出指纹认证界面

**Screenshots**（截图）
无

**Version（发现问题的版本）:**
 - OS: Android 13
 - Version v4.1.1-9-48e0184-row

**Additional context**（其他信息）
稳定复现且已知多人存在此问题，LSP 激活无问题

** Logs**（日志文件）
软重启的log不知道怎么抓…

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本
> 2. Thanox版本，补丁方式（xposed还是magisk？）
> 3. 问题现象的详细描述，有图或者视频更好
> 4. 不激活thanox有问题吗？
> 5. Thanox激活后不做任何配置有问题吗？
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by zzkeier** [comment]
面临同样的问题，附adb logcat
`11-23 12:47:30.906 E/ActivityManager(21168): Sending non-protected broadcast thanox.a.get.patch.sources.Magisk from system 21168:system/1000 pkg android
11-23 12:47:30.906 E/ActivityManager(21168): java.lang.Throwable
11-23 12:47:30.906 E/ActivityManager(21168): 	at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:13523)
11-23 12:47:30.906 E/ActivityManager(21168): 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14245)
11-23 12:47:30.906 E/ActivityManager(21168): 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13541)
11-23 12:47:30.906 E/ActivityManager(21168): 	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:14404)
11-23 12:47:30.906 E/ActivityManager(21168): 	at android.app.ContextImpl.sendStickyBroadcastAsUser(ContextImpl.java:1659)
11-23 12:47:30.906 E/ActivityManager(21168): 	at github.tornaco.android.thanos.services.AndroidPatchSources.publish(Unknown Source:75)
11-23 12:47:30.906 E/ActivityManager(21168): 	at github.tornaco.android.thanos.services.app.ActivityManagerService.lambda$publishPatchSourceInternal$56(Unknown Source:6)
11-23 12:47:30.906 E/ActivityManager(21168): 	at github.tornaco.android.thanos.services.app.ActivityManagerService.M(Unknown Source:0)
11-23 12:47:30.906 E/ActivityManager(21168): 	at androidx.appcompat.widget.y0.run(Unknown Source:10)
11-23 12:47:30.906 E/ActivityManager(21168): 	at eg.d.k(Unknown Source:9)
11-23 12:47:30.906 E/ActivityManager(21168): 	at wf.a.b(SourceFile:2)
11-23 12:47:30.906 E/ActivityManager(21168): 	at eg.f$a.run(Unknown Source:2)
11-23 12:47:30.906 E/ActivityManager(21168): 	at hk.d$b.run(Unknown Source:2)
11-23 12:47:30.906 E/ActivityManager(21168): 	at android.os.Handler.handleCallback(Handler.java:942)
11-23 12:47:30.906 E/ActivityManager(21168): 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-23 12:47:30.906 E/ActivityManager(21168): 	at android.os.Looper.loopOnce(Looper.java:201)
11-23 12:47:30.906 E/ActivityManager(21168): 	at android.os.Looper.loop(Looper.java:288)
11-23 12:47:30.906 E/ActivityManager(21168): 	at android.os.HandlerThread.run(HandlerThread.java:67)
11-23 22:15:19.927 E/        (    0): [2-005a]aw869xx_irq chip ov int error
11-23 12:47:31.248 E/Instrumentation(24967): Uninitialized ActivityThread, likely app-created Instrumentation, disabling AppComponentFactory
11-23 12:47:31.248 E/Instrumentation(24967): java.lang.Throwable
11-23 12:47:31.248 E/Instrumentation(24967): 	at android.app.Instrumentation.getFactory(Instrumentation.java:1337)
11-23 12:47:31.248 E/Instrumentation(24967): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1231)
11-23 12:47:31.248 E/Instrumentation(24967): 	at app.ait.a(SourceFile:87)
11-23 12:47:31.248 E/Instrumentation(24967): 	at app.aio.a(SourceFile:62)
11-23 12:47:31.248 E/Instrumentation(24967): 	at com.iflytek.coreplugin.CorePlugins.enable(SourceFile:163)
11-23 12:47:31.248 E/Instrumentation(24967): 	at app.ecm.a(SourceFile:57)
11-23 12:47:31.248 E/Instrumentation(24967): 	at app.ect.a(SourceFile:149)
11-23 12:47:31.248 E/Instrumentation(24967): 	at app.ecn.a(SourceFile:171)
11-23 12:47:31.248 E/Instrumentation(24967): 	at app.ecn.init(SourceFile:62)
11-23 12:47:31.248 E/Instrumentation(24967): 	at app.ebi.a(SourceFile:531)
11-23 12:47:31.248 E/Instrumentation(24967): 	at app.ebi.a(SourceFile:95)
11-23 12:47:31.248 E/Instrumentation(24967): 	at app.ebj.run(SourceFile:166)
11-23 12:47:31.248 E/Instrumentation(24967): 	at app.fpg.run(SourceFile:130)
11-23 12:47:31.248 E/Instrumentation(24967): 	at app.for.run(SourceFile:58)
11-23 12:47:31.248 E/Instrumentation(24967): 	at app.foy.a(SourceFile:68)
11-23 12:47:31.248 E/Instrumentation(24967): 	at app.foy.run(SourceFile:42)
11-23 12:47:31.248 E/Instrumentation(24967): 	at app.fon.run(SourceFile:41)
11-23 12:47:31.248 E/Instrumentation(24967): 	at java.lang.Thread.run(Thread.java:1012)
11-23 12:47:33.537 E/KeyguardUpdateMonitor(21579): Fp cancellation not received, transitioning to STOPPED
11-23 12:47:36.239 E/JavaBinder(21168): *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
11-23 12:47:36.239 E/JavaBinder(21168): java.lang.RuntimeException: Not implemented. Must override in a subclass.
11-23 12:47:36.239 E/JavaBinder(21168): 	at android.content.Context.getAssociatedDisplayId(Context.java:7115)
11-23 12:47:36.239 E/JavaBinder(21168): 	at com.android.server.biometrics.PreAuthInfo.create(PreAuthInfo.java:108)
11-23 12:47:36.239 E/JavaBinder(21168): 	at com.android.server.biometrics.BiometricService.createPreAuthInfo(BiometricService.java:871)
11-23 12:47:36.239 E/JavaBinder(21168): 	at com.android.server.biometrics.BiometricService.-$$Nest$mcreatePreAuthInfo(Unknown Source:0)
11-23 12:47:36.239 E/JavaBinder(21168): 	at com.android.server.biometrics.BiometricService$BiometricServiceWrapper.canAuthenticate(BiometricService.java:591)
11-23 12:47:36.239 E/JavaBinder(21168): 	at com.android.server.biometrics.AuthService$AuthServiceImpl.canAuthenticate(AuthService.java:312)
11-23 12:47:36.239 E/JavaBinder(21168): 	at android.hardware.biometrics.IAuthService$Stub.onTransact(IAuthService.java:288)
11-23 12:47:36.239 E/JavaBinder(21168): 	at android.os.Binder.execTransactInternal(Binder.java:1280)
11-23 12:47:36.239 E/JavaBinder(21168): 	at android.os.Binder.execTransact(Binder.java:1244)
11-23 12:47:36.255 E/Zygote  (21168): System zygote died with fatal exception
11-23 12:47:36.255 E/Zygote  (21168): java.lang.RuntimeException: Not implemented. Must override in a subclass.
11-23 12:47:36.255 E/Zygote  (21168): 	at android.content.Context.getAssociatedDisplayId(Context.java:7115)
11-23 12:47:36.255 E/Zygote  (21168): 	at com.android.server.biometrics.PreAuthInfo.create(PreAuthInfo.java:108)
11-23 12:47:36.255 E/Zygote  (21168): 	at com.android.server.biometrics.BiometricService.lambda$handleAuthenticate$2$com-android-server-biometrics-BiometricService(BiometricService.java:1223)
11-23 12:47:36.255 E/Zygote  (21168): 	at com.android.server.biometrics.BiometricService$$ExternalSyntheticLambda0.run(Unknown Source:16)
11-23 12:47:36.255 E/Zygote  (21168): 	at android.os.Handler.handleCallback(Handler.java:942)
11-23 12:47:36.255 E/Zygote  (21168): 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-23 12:47:36.255 E/Zygote  (21168): 	at android.os.Looper.loopOnce(Looper.java:201)
11-23 12:47:36.255 E/Zygote  (21168): 	at android.os.Looper.loop(Looper.java:288)
11-23 12:47:36.255 E/Zygote  (21168): 	at com.android.server.SystemServer.run(SystemServer.java:967)
11-23 12:47:36.255 E/Zygote  (21168): 	at com.android.server.SystemServer.main(SystemServer.java:652)
11-23 12:47:36.255 E/Zygote  (21168): 	at java.lang.reflect.Method.invoke(Native Method)
11-23 12:47:36.255 E/Zygote  (21168): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-23 12:47:36.255 E/Zygote  (21168): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:914)
11-23 12:47:36.256 E/AndroidRuntime(21168): *** FATAL EXCEPTION IN SYSTEM PROCESS: main
11-23 12:47:36.256 E/AndroidRuntime(21168): java.lang.RuntimeException: Not implemented. Must override in a subclass.
11-23 12:47:36.256 E/AndroidRuntime(21168): 	at android.content.Context.getAssociatedDisplayId(Context.java:7115)
11-23 12:47:36.256 E/AndroidRuntime(21168): 	at com.android.server.biometrics.PreAuthInfo.create(PreAuthInfo.java:108)
11-23 12:47:36.256 E/AndroidRuntime(21168): 	at com.android.server.biometrics.BiometricService.lambda$handleAuthenticate$2$com-android-server-biometrics-BiometricService(BiometricService.java:1223)
11-23 12:47:36.256 E/AndroidRuntime(21168): 	at com.android.server.biometrics.BiometricService$$ExternalSyntheticLambda0.run(Unknown Source:16)
11-23 12:47:36.256 E/AndroidRuntime(21168): 	at android.os.Handler.handleCallback(Handler.java:942)
11-23 12:47:36.256 E/AndroidRuntime(21168): 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-23 12:47:36.256 E/AndroidRuntime(21168): 	at android.os.Looper.loopOnce(Looper.java:201)
11-23 12:47:36.256 E/AndroidRuntime(21168): 	at android.os.Looper.loop(Looper.java:288)
11-23 12:47:36.256 E/AndroidRuntime(21168): 	at com.android.server.SystemServer.run(SystemServer.java:967)
11-23 12:47:36.256 E/AndroidRuntime(21168): 	at com.android.server.SystemServer.main(SystemServer.java:652)
11-23 12:47:36.256 E/AndroidRuntime(21168): 	at java.lang.reflect.Method.invoke(Native Method)
11-23 12:47:36.256 E/AndroidRuntime(21168): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-23 12:47:36.256 E/AndroidRuntime(21168): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:914)`

**Comment by zzkeier** [comment]
@Tornaco 使用4.1.2 面临同样的问题，附logcat：https://pastebin.mozilla.org/vZvqFcAJ

**Comment by Tornaco** [comment]
@zzkeier 先mark下错误  : *** FATAL EXCEPTION IN SYSTEM PROCESS: main
11-23 12:47:36.256 E/AndroidRuntime(21168): java.lang.RuntimeException: Not implemented. Must override in a subclass.
11-23 12:47:36.256 E/AndroidRuntime(21168):  at android.content.Context.getAssociatedDisplayId(Context.java:7115)
11-23 12:47:36.256 E/AndroidRuntime(21168):  at com.android.server.biometrics.PreAuthInfo.create(PreAuthInfo.java:108)
11-23 12:47:36.256 E/AndroidRuntime(21168):  at com.android.server.biometrics.BiometricService.lambda$handleAuthenticate$2$com-android-server-biometrics-BiometricService(BiometricService.java:1223)
11-23 12:47:36.256 E/AndroidRuntime(21168):  at com.android.server.biometrics.BiometricService$$ExternalSyntheticLambda0.run(Unknown Source:16)
11-23 12:47:36.256 E/AndroidRuntime(21168):  at android.os.Handler.handleCallback(Handler.java:942)
11-23 12:47:36.256 E/AndroidRuntime(21168):  at android.os.Handler.dispatchMessage(Handler.java:99)
11-23 12:47:36.256 E/AndroidRuntime(21168):  at android.os.Looper.loopOnce(Looper.java:201)
11-23 12:47:36.256 E/AndroidRuntime(21168):  at android.os.Looper.loop(Looper.java:288)
11-23 12:47:36.256 E/AndroidRuntime(21168):  at com.android.server.SystemServer.run(SystemServer.java:967)
11-23 12:47:36.256 E/AndroidRuntime(21168):  at com.android.server.SystemServer.main(SystemServer.java:652)
11-23 12:47:36.256 E/AndroidRuntime(21168):  at java.lang.reflect.Method.invoke(Native Method)
11-23 12:47:36.256 E/AndroidRuntime(21168):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-23 12:47:36.256 E/AndroidRuntime(21168):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:914)

**Comment by hexstr** [comment]
同样的问题，暂时把Thanox删了

**Comment by likuozhu** [comment]
同样的问题  希望作者加以修复  辛苦辛苦

**Comment by w1ndy** [comment]
MIUI 14 (Android 13) 同样的问题，logcat报错：

```
12-24 21:39:33.902  2691 10700 D BiometricService: canAuthenticate: User=0, Caller=0, Authenticators=15
12-24 21:39:33.907  2691  2691 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
12-24 21:39:33.907  2691  2691 E AndroidRuntime: java.lang.RuntimeException: Not implemented. Must override in a subclass.
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at android.content.Context.getAssociatedDisplayId(Context.java:7137)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at com.android.server.biometrics.PreAuthInfo.create(PreAuthInfo.java:108)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at com.android.server.biometrics.BiometricService.lambda$handleAuthenticate$2$com-android-server-biometrics-BiometricService(BiometricService.java:1223)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at com.android.server.biometrics.BiometricService$$ExternalSyntheticLambda0.run(Unknown Source:16)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:210)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:299)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:1026)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:704)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
```

换成LSPosed好像就可以了。
