### ISSUE TITLE
开机后一段时间后会导致无法录音

### ISSUE THREAD

**Issue by ZMEMORY** [Tornaco/Thanox#621]
**（现象描述）**
开机后一段时间后会导致无法录音

开机一段时间后(不确定多久，不规律)微信，qq，输入法等除了正常打电话之外都不能用麦克风录音，有时候还会提示录音权限丢失
（简洁的描述该bug的现象）

我开机后就会这样，我也不知道如何算复现（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. Go to '...'（进入XXX）
2. Click on '....'（点击XXX）
3. Scroll down to '....'（下滑到XXX）
4. See error（发现错误XXX）

**Expected behavior**（期望结果）
A clear and concise description of what you expected to happen.（描述一下期望的结果）

**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）

**Version（发现问题的版本）:**
 - OS: [e.g. Android 6.0.1]（系统版本，例如Android 6.0.1）
 - Version [e.g. v2.3.4]（软件版本，例如v2.3.4）

从我去年开始用thanox好像就有这个问题，我是emui9 安卓9.0系统
软件版本直到4.1.1-23都会出现这个问题，酷安评论区好像也有很多酷友会这样
我是用lsp激活的软件，用的是play的最新版

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。

日志有400多行，我截出来了一部分希望有用吧

 2022-11-14 01:15:10.496 W/Thanox-Core: reportOnActivityResumed: Intent { cmp=bin.mt.plus/l.ۘۗۘ }, user: 0
2022-11-14 01:15:10.843 E/Thanox-Core: NotificationRecord#fromLegacy
java.lang.IllegalAccessError: Method 'boolean android.app.Notification.isForegroundService()' is inaccessible to class 'github.tornaco.android.thanos.services.util.NotificationRecordUtils' (declaration of 'github.tornaco.android.thanos.services.util.NotificationRecordUtils' appears in Anonymous-DexFile@0x7271be4000-0x7271f6f47c)
	at github.tornaco.android.thanos.services.util.NotificationRecordUtils.fromStatusBarNotification(Unknown Source:89)
	at github.tornaco.android.thanos.services.xposed.hooks.notification.NMSRegistry$2.afterHookedMethod(Unknown Source:147)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.notifyPosted(Unknown Source:17)
	at com.android.server.notification.NotificationManagerService$NotificationListeners.access$9500(NotificationManagerService.java:7500)
	at com.android.server.notification.NotificationManagerService$NotificationListeners$2.run(NotificationManagerService.java:7640)
	at android.os.Handler.handleCallback(Handler.java:891)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:207)
	at com.android.server.SystemServer.run(SystemServer.java:568)
	at com.android.server.SystemServer.main(SystemServer.java:385)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:938)

2022-11-14 01:15:11.651 E/Thanox-Core: NotificationRecord#fromLegacy
java.lang.IllegalAccessError: Method 'boolean android.app.Notification.isForegroundService()' is inaccessible to class 'github.tornaco.android.thanos.services.util.NotificationRecordUtils' (declaration of 'github.tornaco.android.thanos.services.util.NotificationRecordUtils' appears in Anonymous-DexFile@0x7271be4000-0x7271f6f47c)
	at github.tornaco.android.thanos.services.util.NotificationRecordUtils.fromStatusBarNotification(Unknown Source:89)
	at github.tornaco.android.thanos.services.xposed.hooks.notification.NMSRegistry$2.afterHookedMethod(Unknown Source:147)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.notifyPosted(Unknown Source:17)
	at com.android.server.notification.NotificationManagerService$NotificationListeners.access$9500(NotificationManagerService.java:7500)
	at com.android.server.notification.NotificationManagerService$NotificationListeners$2.run(NotificationManagerService.java:7640)
	at android.os.Handler.handleCallback(Handler.java:891)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:207)
	at com.android.server.SystemServer.run(SystemServer.java:568)
	at com.android.server.SystemServer.main(SystemServer.java:385)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:938)

2022-11-14 01:15:12.136 E/Thanox-Core: NotificationRecord#fromLegacy
java.lang.IllegalAccessError: Method 'boolean android.app.Notification.isForegroundService()' is inaccessible to class 'github.tornaco.android.thanos.services.util.NotificationRecordUtils' (declaration of 'github.tornaco.android.thanos.services.util.NotificationRecordUtils' appears in Anonymous-DexFile@0x7271be4000-0x7271f6f47c)
	at github.tornaco.android.thanos.services.util.NotificationRecordUtils.fromStatusBarNotification(Unknown Source:89)
	at github.tornaco.android.thanos.services.xposed.hooks.notification.NMSRegistry$2.afterHookedMethod(Unknown Source:147)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.notifyPosted(Unknown Source:17)
	at com.android.server.notification.NotificationManagerService$NotificationListeners.access$9500(NotificationManagerService.java:7500)
	at com.android.server.notification.NotificationManagerService$NotificationListeners$2.run(NotificationManagerService.java:7640)
	at android.os.Handler.handleCallback(Handler.java:891)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:207)
	at com.android.server.SystemServer.run(SystemServer.java:568)
	at com.android.server.SystemServer.main(SystemServer.java:385)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:938)

2022-11-14 01:20:07.778 E/Thanox-Core: NotificationRecord#fromLegacy
java.lang.IllegalAccessError: Method 'boolean android.app.Notification.isForegroundService()' is inaccessible to class 'github.tornaco.android.thanos.services.util.NotificationRecordUtils' (declaration of 'github.tornaco.android.thanos.services.util.NotificationRecordUtils' appears in Anonymous-DexFile@0x7271be4000-0x7271f6f47c)
	at github.tornaco.android.thanos.services.util.NotificationRecordUtils.fromStatusBarNotification(Unknown Source:89)
	at github.tornaco.android.thanos.services.xposed.hooks.notification.NMSRegistry$2.afterHookedMethod(Unknown Source:147)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.notifyPosted(Unknown Source:17)
	at com.android.server.notification.NotificationManagerService$NotificationListeners.access$9500(NotificationManagerService.java:7500)
	at com.android.server.notification.NotificationManagerService$NotificationListeners$2.run(NotificationManagerService.java:7640)
	at android.os.Handler.handleCallback(Handler.java:891)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:207)
	at com.android.server.SystemServer.run(SystemServer.java:568)
	at com.android.server.SystemServer.main(SystemServer.java:385)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:938)

2022-11-14 01:20:08.759 E/Thanox-Core: NotificationRecord#fromLegacy
java.lang.IllegalAccessError: Method 'boolean android.app.Notification.isForegroundService()' is inaccessible to class 'github.tornaco.android.thanos.services.util.NotificationRecordUtils' (declaration of 'github.tornaco.android.thanos.services.util.NotificationRecordUtils' appears in Anonymous-DexFile@0x7271be4000-0x7271f6f47c)
	at github.tornaco.android.thanos.services.util.NotificationRecordUtils.fromStatusBarNotification(Unknown Source:89)
	at github.tornaco.android.thanos.services.xposed.hooks.notification.NMSRegistry$2.afterHookedMethod(Unknown Source:147)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.notifyPosted(Unknown Source:17)
	at com.android.server.notification.NotificationManagerService$NotificationListeners.access$9500(NotificationManagerService.java:7500)
	at com.android.server.notification.NotificationManagerService$NotificationListeners$2.run(NotificationManagerService.java:7640)
	at android.os.Handler.handleCallback(Handler.java:891)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:207)
	at com.android.server.SystemServer.run(SystemServer.java:568)
	at com.android.server.SystemServer.main(SystemServer.java:385)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:938)

2022-11-14 01:20:09.651 W/Thanox-Core: AMS onProcessRemovedInternal: ProcessRecord{packageName='com.tencent.mm', processName='com.tencent.mm:appbrand1', pid=0, uid=10209}
2022-11-14 01:20:09.652 W/Thanox-Core: onProcessRemovedInternal, currentFrontPkg: Pkg{pkgName='bin.mt.plus', userId=0}, processPkgName: com.tencent.mm
2022-11-14 01:20:09.686 W/Thanox-Core: AMS onProcessRemovedInternal: ProcessRecord{packageName='com.tencent.mm', processName='com.tencent.mm:appbrand0', pid=0, uid=10209}
2022-11-14 01:20:09.727 W/Thanox-Core: onProcessRemovedInternal, the pkg is still running
2022-11-14 01:20:09.728 W/Thanox-Core: onProcessRemovedInternal, currentFrontPkg: Pkg{pkgName='bin.mt.plus', userId=0}, processPkgName: com.tencent.mm
2022-11-14 01:20:09.731 W/Thanox-Core: onProcessRemovedInternal, the pkg is still running
2022-11-14 01:20:09.757 E/Thanox-Core: NotificationRecord#fromLegacy
java.lang.IllegalAccessError: Method 'boolean android.app.Notification.isForegroundService()' is inaccessible to class 'github.tornaco.android.thanos.services.util.NotificationRecordUtils' (declaration of 'github.tornaco.android.thanos.services.util.NotificationRecordUtils' appears in Anonymous-DexFile@0x7271be4000-0x7271f6f47c)
	at github.tornaco.android.thanos.services.util.NotificationRecordUtils.fromStatusBarNotification(Unknown Source:89)
	at github.tornaco.android.thanos.services.xposed.hooks.notification.NMSRegistry$2.afterHookedMethod(Unknown Source:147)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.notifyPosted(Unknown Source:17)
	at com.android.server.notification.NotificationManagerService$NotificationListeners.access$9500(NotificationManagerService.java:7500)
	at com.android.server.notification.NotificationManagerService$NotificationListeners$2.run(NotificationManagerService.java:7640)
	at android.os.Handler.handleCallback(Handler.java:891)
	at android.os.Handler.dispatchMess

我就是个小白，如果反馈有什么问题，希望作者大大不要见怪😂

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本
> 2. Thanox版本，补丁方式（xposed还是magisk？）
> 3. 问题现象的详细描述，有图或者视频更好
> 4. 不激活thanox有问题吗？
> 5. Thanox激活后不做任何配置有问题吗？
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by ZMEMORY** [comment]
对了，我没有开乖巧和情景模式，只用来做后台管理

**Comment by ZMEMORY** [comment]
不激活thanox的情况下，我目前的使用习惯里没出现过类似的现象(我手机基本一天会重启一次)

**Comment by PoseidonWake** [comment]
我也是，之前出现过一次微信无法录音的现象，提示没权限，重启好了，不过之后似乎再没复现过，但我这儿用一段时间必然会出现输入法振动失效的问题，这个时间看起来是随机的，有时候刚开机，有时是好几天，而我对输入法没做任何配置，情景模式里也没有任何涉及输入法的配置
