### ISSUE TITLE
求问对于PM suspend的应用如何通过命令行resume

### ISSUE THREAD

**Issue by n374** [Tornaco/Thanox#622]
Hi, 我当前使用LMT Launcher来运行`am start`命令快速打开支付宝的扫码页面，在使用thanox将支付宝Freeze(PM suspend)后，`am start`会有"Action not allowed. If you have questions, contact your IT admin"报错
![telegram-cloud-photo-size-1-5742344092360222653-y](https://user-images.githubusercontent.com/4954114/202493033-6db2ba08-f4ac-4868-9e27-eb8c56921e50.jpg)
推测是因为当前应用处于suspend状态中无法直接`am start`，所以尝试在`am start`前用`pm unsuspend`命令先恢复

使用root用户会有如上报错：
``` bash
OnePlus6T:/ # pm unsuspend com.eg.android.AlipayGphone
Package com.eg.android.AlipayGphone new suspended state: true
OnePlus6T:/ # am start -n com.eg.android.AlipayGphone/com.alipay.mobile.onsitepay9.payer.OspTabHostActivity
Starting: Intent { cmp=com.eg.android.AlipayGphone/com.alipay.mobile.onsitepay9.payer.OspTabHostActivity }
```

尝试在参数中指定thanox的用户，报错依旧
``` bash
OnePlus6T:/ # dumpsys package github.tornaco.android.thanos.pro | grep userId
    userId=10565
OnePlus6T:/ # pm unsuspend --user 10565 com.eg.android.AlipayGphone
Package com.eg.android.AlipayGphone new suspended state: false
OnePlus6T:/ # am start -n com.eg.android.AlipayGphone/com.alipay.mobile.onsitepay9.payer.OspTabHostActivity
Starting: Intent { cmp=com.eg.android.AlipayGphone/com.alipay.mobile.onsitepay9.payer.OspTabHostActivity }
```

尝试切换到thanox用户执行命令，直接报错
``` bash
OnePlus6T:/ # su - $(id -un 10565)
OnePlus6T:/ $ pm unsuspend com.eg.android.AlipayGphone

Exception occurred while executing 'unsuspend':
java.lang.SecurityException: setPackagesSuspendedAsUser: Neither user 10565 nor current process has android.permission.SUSPEND_APPS.
        at android.app.ContextImpl.enforce(ContextImpl.java:2055)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2083)
        at com.android.server.pm.PackageManagerService.enforceCanSetPackagesSuspendedAsUser(PackageManagerService.java:13921)
        at com.android.server.pm.PackageManagerService.setPackagesSuspendedAsUser(PackageManagerService.java:13941)
        at com.android.server.pm.PackageManagerShellCommand.runSuspend(PackageManagerShellCommand.java:2272)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:250)
        at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
        at android.os.ShellCommand.exec(ShellCommand.java:44)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22527)
        at android.os.Binder.shellCommand(Binder.java:940)
        at android.os.Binder.onTransact(Binder.java:824)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4664)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4583)
        at android.os.Binder.execTransactInternal(Binder.java:1170)
        at android.os.Binder.execTransact(Binder.java:1134)
```

而不通过thanox freeze直接在adb中`pm suspend`后再`pm unsuspend`，是能正常执行`am start`并唤起扫码页面的
``` bash
OnePlus6T:/ # pm suspend com.eg.android.AlipayGphone
Package com.eg.android.AlipayGphone new suspended state: true
OnePlus6T:/ # pm unsuspend com.eg.android.AlipayGphone
Package com.eg.android.AlipayGphone new suspended state: false
OnePlus6T:/ # am start -n com.eg.android.AlipayGphone/com.alipay.mobile.onsitepay9.payer.OspTabHostActivity
Starting: Intent { cmp=com.eg.android.AlipayGphone/com.alipay.mobile.onsitepay9.payer.OspTabHostActivity }
```

所以想问一下如何能通过命令行的方式恢复freeze的应用，感谢

- Thanox 4.0.8-row
- Magisk 25.2
- Zygisk - Thanox 4.1.2
- OnePlus 6T
- OxygenOS 11.1.2.2
- Android 11

**Comment by Tornaco** [comment]
@n374 原因未知，猜测可能跟调用方身份有关，我会暴露一个解冻的shell命令，直接用shell命令调用thanox解冻应该可以解决这类问题。

**Comment by n374** [comment]
我今天把系统刷成了基于Android 13的EvolutionX 7.3，同时从Magisk Zygisk模式切换到了LSPosed，随后发现`am start`不再需要`pm unsuspend`就能正常执行了🤡，不确定之前的现象是Android版本的问题还是OOS有调整过什么

**Comment by Tornaco** [comment]
如果需要的话，可以使用下面的命令解冻：
`adb shell dumpsys tv_input unfreeze [pkg name] [userId]`

举例：
`adb shell dumpsys tv_input unfreeze com.tencent.mm 0`
