### ISSUE TITLE
Bug反馈——在激活thanox后，微信指纹支付时手机会重启

### ISSUE THREAD

**Issue by wmdzb** [Tornaco/Thanox#629]
问题：在激活thanox后，微信指纹支付时手机会重启。
尝试：在我发现问题之后，首先卸载了面具和thanox，后重新安装。面具安装及激活后均无问题产生。激活thanox时，即在面具中安装Zygisk-Thanox模块后，问题发生，微信弹出指纹支付时直接重启。关闭Zygisk-Thanox模块后再次尝试微信指纹支付，没有发生重启现象。支付完成。 
软件版本：magisk 25.3,Thanox 4.1.4-prc;  Android版本 13.（pixel experience rom）

**Comment by w1ndy** [comment]
在MIUI 14 (Android 13)上也遇到同样问题，通过zygisk运行Thanox会出现指纹无法使用的情况，比如Magisk中切换生物识别验证时/1Password解锁时手机会直接重启，而通过LSPosed运行貌似没有这样的问题。重启时抛出的异常如下：

```
12-24 21:39:33.902  2691 10700 D BiometricService: canAuthenticate: User=0, Caller=0, Authenticators=15
12-24 21:39:33.907  2691  2691 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
12-24 21:39:33.907  2691  2691 E AndroidRuntime: java.lang.RuntimeException: Not implemented. Must override in a subclass.
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at android.content.Context.getAssociatedDisplayId(Context.java:7137)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at com.android.server.biometrics.PreAuthInfo.create(PreAuthInfo.java:108)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at com.android.server.biometrics.BiometricService.lambda$handleAuthenticate$2$com-android-server-biometrics-BiometricService(BiometricService.java:1223)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at com.android.server.biometrics.BiometricService$$ExternalSyntheticLambda0.run(Unknown Source:16)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:210)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:299)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:1026)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:704)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
12-24 21:39:33.907  2691  2691 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
```

**Comment by DaFeiLian** [comment]
问题：在使用magisk模块激活thanox后，在开启magisk中“超级用户→生物识别验证”后时，赋予应用或取消应用超级用户权限时手机会重启，在使用“google自动填充”功能填充记录的账号密码时，选择账号后将要弹出指纹验证窗口（还未弹出）时手机重启。
尝试：关闭magisk激活thanox模块后未出现此问题。
软件版本：magisk 25.2,Thanox 4.1.4-prc; Android版本 13.（pixel experience rom）
机型：红米K40

**Comment by DaFeiLian** [comment]
> 问题：在使用magisk模块激活thanox后，在开启magisk中“超级用户→生物识别验证”后时，赋予应用或取消应用超级用户权限时手机会重启，在使用“google自动填充”功能填充记录的账号密码时，选择账号后将要弹出指纹验证窗口（还未弹出）时手机重启。 尝试：关闭magisk激活thanox模块后未出现此问题。 软件版本：magisk 25.2,Thanox 4.1.4-prc; Android版本 13.（pixel experience rom） 机型：红米K40

**Comment by DaFeiLian** [comment]
[2023-01-24.txt](https://github.com/Tornaco/Thanox/files/10487156/2023-01-24.txt)

**Comment by DaFeiLian** [comment]
[2023-01-24.txt](https://github.com/Tornaco/Thanox/files/10487158/2023-01-24.txt)
日志文件
