### ISSUE TITLE
Framework error

### ISSUE THREAD

**Issue by lingfantang** [Tornaco/Thanox#640]
**Describe the bug（现象描述）**
Framework error

<del>**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）</del>
<del>1. Go to '...'（进入XXX）
2. Click on '....'（点击XXX）
3. Scroll down to '....'（下滑到XXX）
4. See error（发现错误XXX）</del>

<del>**Expected behavior**（期望结果）
A clear and concise description of what you expected to happen.（描述一下期望的结果）</del>

**Screenshots**（截图）
![Screenshot_20230115-114511](https://user-images.githubusercontent.com/56295323/212522192-e7c0afc3-5515-45e0-b1ba-d0167add7921.png)

**Version（发现问题的版本）:**
 - OS: Android 12
 - Version 
![Screenshot_20230115-114448](https://user-images.githubusercontent.com/56295323/212522158-e3e35bc3-91c5-4bbe-9d73-9b4519a5d06d.png)

**Additional context**（其他信息）
Sony XQ-AT52
```
2023-01-15 04:55:35.135 E/Thanox-Core: java.lang.NullPointerException: Parameter specified as non-null is null: method github.tornaco.android.thanos.services.app.ProcessStartCheckHelperKt.isActivity, parameter hostType
	at github.tornaco.android.thanos.services.app.ProcessStartCheckHelperKt.isActivity(Unknown Source:2)
	at github.tornaco.android.thanos.services.app.ActivityManagerService.checkStartProcessInternal(Unknown Source:217)
	at github.tornaco.android.thanos.services.app.ActivityManagerService.lambda$checkStartProcess$19(Unknown Source:0)
	at github.tornaco.android.thanos.services.app.ActivityManagerService.C(Unknown Source:0)
	at github.tornaco.android.thanos.services.app.e0.g(Unknown Source:11)
	at hg.a.i(Unknown Source:10)
	at wf.j.a(SourceFile:2)
	at hg.c.i(Unknown Source:7)
	at wf.j.a(SourceFile:2)
	at hg.g.i(Unknown Source:7)
	at wf.j.a(SourceFile:2)
	at hg.i.i(Unknown Source:38)
	at wf.j.a(SourceFile:2)
	at wf.j.b(Unknown Source:5)
	at github.tornaco.android.thanos.services.app.ActivityManagerService.checkStartProcess(Unknown Source:43)
	at github.tornaco.android.thanos.services.xposed.hooks.q.core.AMSStartProcessLockedRegistry$1.beforeHookedMethod(Unknown Source:175)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.startProcessLocked(Unknown Source:78)
	at com.android.server.am.ActivityManagerService.startProcessLocked(ActivityManagerService.java:2744)
	at com.android.server.am.ActivityManagerService.startActivityAsUserEmpty(ActivityManagerService.java:3029)
	at com.android.server.am.ActivityManagerService$LocalService.startActivityAsUserEmpty(ActivityManagerService.java:15816)
	at com.android.server.wm.ActivityTaskSupervisor$PreferredAppsTask$$ExternalSyntheticLambda0.accept(Unknown Source:4)
	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:281)
	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:204)
	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:346)
	at android.os.Looper.loop(Looper.java:475)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:44)
```

** Logs**（日志文件）
看了一下觉得其他日志的时间对不上就只上传了一部分。
[thanox-core.log](https://github.com/Tornaco/Thanox/files/10419426/thanox-core.log)

**Comment by Tornaco** [comment]
OK，日志够了。

**Comment by Tornaco** [comment]
@lingfantang   试下这个：

https://app.circleci.com/pipelines/github/Tornaco/Thanox/554/workflows/091df1ca-3384-4202-a76b-640321b23d25/jobs/503/artifacts

**Comment by lingfantang** [comment]
> @lingfantang 试下这个：
> 
> https://app.circleci.com/pipelines/github/Tornaco/Thanox/554/workflows/091df1ca-3384-4202-a76b-640321b23d25/jobs/503/artifacts

@Tornaco 这么久以来这个error我总共也就碰过这一次，所以也不清楚怎么复现。到底修好了没我不知道，但是这个新版本我用了一晚上倒没啥毛病。
