### ISSUE TITLE
Cos13系统用magisk激活thanox会导致相机闪退打不开

### ISSUE THREAD

**Issue by CC781702761** [Tornaco/Thanox#643]
Cos13系统用magisk激活thanox会导致相机闪退打不开
> 1. 系统版本 cos13
> 2. magisk激活
> 3. Cos13系统用magisk激活thanox会导致相机闪退打不开
> 4. 不激活thanox没问题 lsp激活也没问题 但是因为我使用的一些软件和lsp激活有冲突 所以希望修复cos13面具激活相机闪退的问题 谢谢

**Comment by CC781702761** [comment]
[Uploading log.zip…]()

**Comment by aki-0929** [comment]
解决了吗

**Comment by Tornaco** [comment]
@aki-0929 cos目前无解，建议还是用lsp算了

**Comment by aki-0929** [comment]
> @aki-0929 cos目前无解，建议还是用lsp算了

我不闪退了 
我这边是更新了最新的5.0.1-prc
magisk开启zygisk
然后用了shamiko模块
把相机加入排除列表

**Comment by Tornaco** [comment]
@aki-0929 头疼😂

**Comment by Harry-Chen** [comment]
Reproducible with ColorOS 14, OnePlus Camera 4.040.553, Thanox Pro 5.1.6.

Related logs:

```
11-19 09:15:21.763 20665 20665 W OCAM_DeviceUtil: initScreenHeightWidth, sScreenHeight: 2412, sScreenWidth: 1080, folderOpen: false
11-19 09:15:21.764 20665 20665 E AndroidRuntime: FATAL EXCEPTION: main
11-19 09:15:21.764 20665 20665 E AndroidRuntime: Process: com.oplus.camera, PID: 20665
11-19 09:15:21.764 20665 20665 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.Size.getWidth()' on a null object reference
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at com.oplus.camera.module.BaseMode.wb(BaseMode.java:163)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at ff.g1.Sc(CommonCapMode.java:103)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at hf.k0.Sc(QuickCaptureMode.java:1)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at androidx.window.embedding.c.run(R8$$SyntheticClass:300)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at j6.k.e(ThreadManager.java:7)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at ff.g1.Ha(CommonCapMode.java:51)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at hf.k0.Ha(QuickCaptureMode.java:11)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at com.oplus.camera.module.BaseMode.ea(BaseMode.java:48)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at ff.g1.ea(CommonCapMode.java:1)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at g7.y.accept(R8$$SyntheticClass:155)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at u7.d.b(R8$$SyntheticClass:85)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at eg.a.e(Event.java:24)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at com.oplus.camera.module.processor.captureprocessor.CaptureProcessor.l(CaptureProcessor.java:94)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at com.oplus.camera.module.processor.captureprocessor.CaptureProcessor.j(CaptureProcessor.java:21)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at com.oplus.camera.module.processor.captureprocessor.CaptureProcessor.x(CaptureProcessor.java:82)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at kf.e0.run(R8$$SyntheticClass:42)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:257)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:368)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8839)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
11-19 09:15:21.764 20665 20665 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

Maybe this can help debugging. @Tornaco
