### ISSUE TITLE
4.2.0無法激活，4.1.9正常

### ISSUE THREAD

**Issue by diedbug2002** [Tornaco/Thanox#683]
**Describe the bug（现象描述）**
→4.2.0無法激活，4.1.9正常

**To Reproduce**（如何复现）
→更新後重啟顯示未激活

**Expected behavior**（期望结果）
→成功激活

**Screenshots**（截图）
→無

**Version（发现问题的版本）:**
→OS：android 12
→Thanox：4.2.0-row（激活方式：lsp 6900）

**Additional context**（其他信息）
→無

** Logs**（日志文件）
→data/system/thanox內log為空（可能因為沒激活，所以沒產生LOG？）

**Comment by Tornaco** [comment]
@diedbug2002 重新在lsp里勾选重启有用吗？ LSP版本是多少？ 没有日志的话，发一下lsp日志，否则没法定位问题。

**Comment by diedbug2002** [comment]
> @diedbug2002 重新在lsp里勾选重启有用吗？ LSP版本是多少？ 没有日志的话，发一下lsp日志，否则没法定位问题。

LPS 1.8.6（6900），請見Version內說明，lsp日誌稍等

**Comment by Tornaco** [comment]
@diedbug2002  定位到原因了，我一会推个新版本给你试试。麻烦留下你的google邮箱地址。单独推送给你。

**Comment by diedbug2002** [comment]
> @diedbug2002 定位到原因了，我一会推个新版本给你试试。麻烦留下你的google邮箱地址。单独推送给你。

diedbug2002@gmail.com

請問還是4.2.0？還是新版本號？

謝謝

**Comment by Tornaco** [comment]
@diedbug2002 你现在试试，能检测到4.2.1更新了吗？

**Comment by diedbug2002** [comment]
> @diedbug2002 你现在试试，能检测到4.2.1更新了吗？

還是4.2.0，該不會要等個幾天才推來XDDDD

**Comment by Tornaco** [comment]
@diedbug2002 https://play.google.com/apps/internaltest/4699745136264046535 加一下测试计划

**Comment by diedbug2002** [comment]
> @diedbug2002 https://play.google.com/apps/internaltest/4699745136264046535 加一下测试计划

已加入

**Comment by Tornaco** [comment]
@diedbug2002 好，没有检测到的话，再等等看

**Comment by diedbug2002** [comment]
> @diedbug2002 好，没有检测到的话，再等等看

@Tornaco 
已收到4.2.1，但仍無法激活
重新在lsp里勾选重启有用吗？→也無法
lsp日誌要給你哪個檔案？需要詳細日誌？

verbose中看到似乎是異常訊息，一併貼上

[ 2023-05-30T10:56:09.806        0:   920:  1013 W/LSPosedService  ] failed to parse parse /data/app/~~6e8guWn49KUXWhbsXkn0YA==/github.tornaco.android.thanos.pro-pvoWqRu2WXpY8k9wbJHw5g==/base.apk
android.content.pm.PackageParser$PackageParserException: Failed to read manifest from /data/app/~~6e8guWn49KUXWhbsXkn0YA==/github.tornaco.android.thanos.pro-pvoWqRu2WXpY8k9wbJHw5g==/base.apk
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1252)
	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1198)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1102)
	at W0.s(Unknown Source:165)
	at s1.b(Unknown Source:24)
	at f1.onTransact(Unknown Source:197)
	at s1.onTransact(Unknown Source:12)
	at android.os.Binder.execTransactInternal(Binder.java:1215)
	at android.os.Binder.execTransact(Binder.java:1179)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.permission.PermissionManager.getSplitPermissions()' on a null object reference
	at android.content.pm.PackageParser.parseBaseApkCommon(PackageParser.java:2422)
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1913)
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1236)
	... 8 more

[ 2023-05-30T10:56:20.429        0:   920:  5848 W/LSPosedService  ] failed to parse parse /data/app/~~6e8guWn49KUXWhbsXkn0YA==/github.tornaco.android.thanos.pro-pvoWqRu2WXpY8k9wbJHw5g==/base.apk
android.content.pm.PackageParser$PackageParserException: Failed to read manifest from /data/app/~~6e8guWn49KUXWhbsXkn0YA==/github.tornaco.android.thanos.pro-pvoWqRu2WXpY8k9wbJHw5g==/base.apk
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1252)
	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1198)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1102)
	at W0.s(Unknown Source:165)
	at s1.b(Unknown Source:24)
	at f1.onTransact(Unknown Source:169)
	at s1.onTransact(Unknown Source:12)
	at android.os.Binder.execTransactInternal(Binder.java:1215)
	at android.os.Binder.execTransact(Binder.java:1179)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.permission.PermissionManager.getSplitPermissions()' on a null object reference
	at android.content.pm.PackageParser.parseBaseApkCommon(PackageParser.java:2422)
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1913)
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1236)
	... 8 more

**Comment by Tornaco** [comment]
@diedbug2002 导出lsp日志就行了

**Comment by diedbug2002** [comment]
> @diedbug2002 导出lsp日志就行了

@Tornaco 來了
[LSPosed_2023-05-30T10_59_08.182.zip](https://github.com/Tornaco/Thanox/files/11595490/LSPosed_2023-05-30T10_59_08.182.zip)

**Comment by Tornaco** [comment]
@diedbug2002 看了下日志里的错误，目前看起来是Lsp加载模块报错了，为了找root cause，我自己打包了lsp6900，在里面加了一些定位问题的日志，麻烦试试我这个lsp包，完了把lsp日志发下。

[LSPosed-v1.8.6-6900-zygisk-debug.zip](https://github.com/Tornaco/Thanox/files/11596426/LSPosed-v1.8.6-6900-zygisk-debug.zip)

**Comment by Tornaco** [comment]
@diedbug2002 另外我测试了手里的几台设备，都是没复现这个问题，所以不确定是不是个别设备上的奇怪问题。

**Comment by diedbug2002** [comment]
> @diedbug2002 看了下日志里的错误，目前看起来是Lsp加载模块报错了，为了找root cause，我自己打包了lsp6900，在里面加了一些定位问题的日志，麻烦试试我这个lsp包，完了把lsp日志发下。
> 
> [LSPosed-v1.8.6-6900-zygisk-debug.zip](https://github.com/Tornaco/Thanox/files/11596426/LSPosed-v1.8.6-6900-zygisk-debug.zip)


@Tornaco 
有沒有riru的？我沒有用zygisk（會不會是這個差異導致？）

**Comment by diedbug2002** [comment]
> @diedbug2002 另外我测试了手里的几台设备，都是没复现这个问题，所以不确定是不是个别设备上的奇怪问题。

希望不是，不然一路更新用到現在，就只好在6.1.9止步了

**Comment by Tornaco** [comment]
@diedbug2002  riru 刚打包

[LSPosed-v1.8.6-6900-riru-debug.zip](https://github.com/Tornaco/Thanox/files/11597176/LSPosed-v1.8.6-6900-riru-debug.zip)

**Comment by diedbug2002** [comment]
> 

@Tornaco 來了
[LSPosed_2023-05-30T15_31_00.930.zip](https://github.com/Tornaco/Thanox/files/11597292/LSPosed_2023-05-30T15_31_00.930.zip)

**Comment by smanlin** [comment]
遭遇同樣問題，起始splash顯示棒棒哒，進app又顯示未激活，所有配置丟失，移花接木設置丟失
[LSPosed_2023-05-30T16_34_35.944.zip](https://github.com/Tornaco/Thanox/files/11597820/LSPosed_2023-05-30T16_34_35.944.zip)

**Comment by Tornaco** [comment]
@diedbug2002 又推了一个新版本，4.2.1-1-00ca332，一会你再试试吧。目前看是lsposed框架兼容性问题，暂时把hook入口回退到经典模式了。

**Comment by diedbug2002** [comment]
> @diedbug2002 又推了一个新版本，4.2.1-1-00ca332，一会你再试试吧。目前看是lsposed框架兼容性问题，暂时把hook入口回退到经典模式了。

@Tornaco  4.2.1-1成功激活！！！ cheers
