### ISSUE TITLE
启动时log中有报错

### ISSUE THREAD

**Issue by NuoFang6** [Tornaco/Thanox#716]
会重新出现几遍，不确定有什么影响
`[ 1970-01-01T08:00:22.669        0:  4148:  4148 I/Magisk          ] * Launching zygiskd32
[ 1970-01-01T08:00:22.671        0:  4148:  4149 I/LSPosed         ] ZygiskCompanion: welcome to LSPosed!
[ 1970-01-01T08:00:22.671        0:  4148:  4149 I/LSPosed         ] ZygiskCompanion: version v1.8.6 (6951)
[ 2023-01-01T00:00:15.221     1000:  2897:  2897 I/LSPosed-Bridge  ] Adding TV input service @java.lang.Throwable
	at github.tornaco.android.thanos.services.xposed.hooks.ServiceManagerRegistry$1.beforeHookedMethod(SourceFile:2)
	at DRfKa.yngcRFYRxGgPlMln.XposedBridge$AdditionalHookInfo.callback(Unknown Source:99)
	at LSPHooker_.addService(Unknown Source:18)
	at github.tornaco.android.thanos.services.ThanoxServicePublisher.tryInstallReplaced(Unknown Source:5)
	at github.tornaco.android.thanos.services.ThanoxServicePublisher.publish(Unknown Source:17)
	at github.tornaco.android.thanos.services.ThanosService.publishBinderService(Unknown Source:9)
	at github.tornaco.android.thanos.services.ThanosService.systemReady(Unknown Source:14)
	at github.tornaco.android.thanos.services.BootStrap.ready(Unknown Source:6)
	at github.tornaco.android.thanos.services.xposed.hooks.AMSBasicRegistry$2.afterHookedMethod(Unknown Source:3)
	at DRfKa.yngcRFYRxGgPlMln.XposedBridge$AdditionalHookInfo.callback(Unknown Source:204)
	at LSPHooker_.systemReady(Unknown Source:14)
	at com.android.server.SystemServer.startOtherServices(SystemServer.java:3084)
	at com.android.server.SystemServer.run(SystemServer.java:1019)
	at com.android.server.SystemServer.main(SystemServer.java:669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:991)`

**Comment by Tornaco** [comment]
不影響，鑒於大家問了多次，後續會刪除。
