### ISSUE TITLE
“打开其他应用”功能存在问题

### ISSUE THREAD

**Issue by funnycups** [Tornaco/Thanox#825]
**Describe the bug（现象描述）**
如果把IDM+、Nagram等软件“打开其他应用”设置为询问，那么在使用它们打开apk调起Installerx时，会提示：
java.lang.SecurityException: Permission Denial: opening provider androidx.core.content.FileProvider from ProcessRecord{e9b8d24 11651:com.rosan.installer.x/u0a390} (pid=11651, uid=10390) that is not exported from UID 10362
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6415)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7862)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3705)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2545)
	at android.content.ContentResolver.acquireUnstableContentProviderClient(ContentResolver.java:2622)
	at m6.m.i(SourceFile:263)
	at m6.m.i(SourceFile:18)
	at m6.m.i(SourceFile:18)
	at m6.m.i(SourceFile:18)
	at m6.m.h(SourceFile:252)
	at m6.l.s(SourceFile:13)
	at x7.a.q(SourceFile:1)
	at n8.e0.run(SourceFile:1)
	at n.h.run(SourceFile:12)
	at t8.i.run(SourceFile:1)
	at t8.a.run(SourceFile:92)

如果把打开应用的权限直接设置成运行，则可以直接调起Installerx打开apk文件

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 打开IDM+
2. 下载任意一个apk文件
3. 打开该文件，在Thanox弹出的打开应用申请的对话框上选择允许
4. Installerx无法读取打开的文件，并报错

**Expected behavior**（期望结果）
Installerx正常被调起并打开apk文件

**Screenshots**（截图）
![Screenshot_2024-02-12-18-41-15-556_com rosan installer x-edit](https://github.com/Tornaco/Thanox/assets/105932603/86a655e6-72a7-4b8c-9b38-b725fa9eee0b)

**Version（发现问题的版本）:**
 - OS: Android14 HyperOS1.0.3.0.UMNEUXM
 - Version 5.0.5-prc

**Additional context**（其他信息）
使用Kiwi Browser打开apk文件时不会发生这样的错误，在Thanox的弹窗选择允许即可正常调起Installerx

** Logs**（日志文件）
[Thanox-Log-2024-02-12-18_33_54.zip](https://github.com/Tornaco/Thanox/files/14237419/Thanox-Log-2024-02-12-18_33_54.zip)

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本
> 2. Thanox版本，补丁方式（xposed还是magisk？）
> 3. 问题现象的详细描述，有图或者视频更好
> 4. 不激活thanox有问题吗？
> 5. Thanox激活后不做任何配置有问题吗？
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by Tornaco** [comment]
@funnycups 试试这个 https://app.circleci.com/pipelines/github/Tornaco/Thanox/940/workflows/aac316e2-93de-4207-b532-03e1772c6897/jobs/844/artifacts

**Comment by funnycups** [comment]
> @funnycups 试试这个 https://app.circleci.com/pipelines/github/Tornaco/Thanox/940/workflows/aac316e2-93de-4207-b532-03e1772c6897/jobs/844/artifacts

这个没问题了

**Comment by Tornaco** [comment]
> > @funnycups 试试这个 https://app.circleci.com/pipelines/github/Tornaco/Thanox/940/workflows/aac316e2-93de-4207-b532-03e1772c6897/jobs/844/artifacts
> 
> 这个没问题了

OK 感谢，这个功能会重新设计以实现更精细的控制。
