### ISSUE TITLE
Play beta 激活后开启应用闪退

### ISSUE THREAD

**Issue by snovvessel** [Tornaco/Thanox#91]
**Describe the bug（现象描述）**
更新后打开应用时会卡住或几秒后黑屏自动重启（像是是重启，若此时回到桌面或切换应用后台好像会自动结束 在应用信息中强制关闭是暗的）

**To Reproduce**（如何复现）
可能是特定bug
更新 play-beta 1.1.6-row 激活重启后会触发

**Expected behavior**（期望结果）
在下一个版本不会闪退

**Screenshots**（截图）

![现象](https://user-images.githubusercontent.com/61366719/75101758-c4db4980-561c-11ea-86cc-3e3271eae13a.gif)

**Version（发现问题的版本）:**
 - OS: 魅蓝note6 MIUI10 7.1.2
 - Version play-beta 1.1.6-row

**Additional context**（其他信息）
现在回退到正式版没有问题 
取消激活后可以打开 但在 设置-开发者 中 开启日志 和 全局白名单 是关闭的（不知道是不是原本就这样）
重新安装beta版激活后启动有时会有核心启动的通知

** Logs**（日志文件）
并未在Android的文件夹下发现logging文件夹但有个logs文件夹（在正式版中和更新后未激活重启状态下 确认开启日志 更新beta版后也不会有）
data中有logging文件夹

[logs.zip](https://github.com/Tornaco/Thanox/files/4240482/logs.zip)
[logging.zip](https://github.com/Tornaco/Thanox/files/4240483/logging.zip)

**Comment by Tornaco** [comment]
```
1582415670469|E|ThanosS|==== Thanos un-handled error, please file a bug ====
1582415670470|E|ThanosS|java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
	at j.a.b.d$b.run()
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.lang.NoSuchMethodError: No virtual method getInstalledApplicationsAsUser(II)Ljava/util/List; in class Landroid/content/pm/PackageManager; or its super classes (declaration of 'android.content.pm.PackageManager' appears in /system/framework/framework.jar)
	at github.tornaco.android.thanos.core.util.PkgUtils.getInstalledApplicationsAsUser()
	at github.tornaco.android.thanos.services.pm.PkgPool.loadAllInstalledApps()
	at github.tornaco.android.thanos.services.pm.PkgPool.invalidateAll()
	at github.tornaco.android.thanos.services.pm.PkgManagerService.initPkgPoolForUser()
	at github.tornaco.android.thanos.services.pm.PkgManagerService.a()
	at github.tornaco.android.thanos.services.pm.b.accept(lambda)
	at util.CollectionUtils.consumeRemaining()
	at github.tornaco.android.thanos.services.pm.PkgManagerService.initPkgPools()
	at github.tornaco.android.thanos.services.pm.PkgManagerService.systemReady()
	at github.tornaco.android.thanos.services.j.run(lambda)
	at c.a.u.e.a.d.b()
	at c.a.b.a()
	at c.a.u.e.a.h$a.run()
	... 5 more

```

这个版本加了多用户的一些逻辑。Android N只有这个API。。我会处理下。
```
public abstract List<ApplicationInfo> getInstalledApplications(@ApplicationInfoFlags int flags);
```

**Comment by Tornaco** [comment]
@Salticat 辛苦测试下最新版本。1.1.7-row Play商店。

**Comment by Tornaco** [comment]
Close for now.
