### ISSUE TITLE
LSposed激活thanox会导致“One UI主屏幕”崩溃

### ISSUE THREAD

**Issue by rannj** [Tornaco/Thanox#970]
**Describe the bug（现象描述）**
经多次测试，发现LSposed激活thanod会导致“One UI主屏幕”崩溃，而使用zygisk激活时则不会出现此问题。

**To Reproduce**（如何复现）
如现象描述

**Expected behavior**（期望结果）
修复此问题

**Screenshots**（截图）

**Version（发现问题的版本）:**
三星One UI 6.1，安卓14，内核5.15.148-android13-8-g7d48a78b36c8

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
[Thanox-Log-2024-08-05-19_21_10.zip](https://github.com/user-attachments/files/16494939/Thanox-Log-2024-08-05-19_21_10.zip)

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本
> 2. Thanox版本，补丁方式（xposed还是magisk？）
> 3. 问题现象的详细描述，有图或者视频更好
> 4. 不激活thanox有问题吗？
> 5. Thanox激活后不做任何配置有问题吗？
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by Tornaco** [comment]
日志如下，建议你检查一下配置，是不是禁止了日志中的provider。也可以尝试恢复默认配置。

```
2024-08-05 12:49:16.758 E/Thanox-Core: onApplicationCrashing: 5.1.1-3080383-thanox@tornaco:a973c892-3f95-4489-ab91-9d1fc8f0fa15	crash	com.sec.android.app.launcher	ProcessRecord{packageName='com.sec.android.app.launcher', processName='com.sec.android.app.launcher', pid=4748, uid=10155}	com.sec.android.app.launcher.plugins.PluginManagerImpl$CrashWhilePluginActiveException: java.lang.IllegalArgumentException: Unknown authority com.samsung.android.app.homestar.provider
	at com.sec.android.app.launcher.plugins.PluginManagerImpl$PluginExceptionHandler.uncaughtException(Unknown Source:57)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1071)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1066)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(Unknown Source:60)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(Unknown Source:14)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Unknown Source:4)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(Unknown Source:56)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(Unknown Source:121)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(Unknown Source:41)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(Unknown Source:4)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(Unknown Source:6)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:35)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:102)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)
Caused by: java.lang.IllegalArgumentException: Unknown authority com.samsung.android.app.homestar.provider
	at android.content.ContentResolver.call(ContentResolver.java:2463)
	at android.content.ContentResolver.call(ContentResolver.java:2446)
	at com.samsung.android.app.homestar.apps.AppsList.setFeatureState(Unknown Source:21)
	at p8.n.invokeSuspend(Unknown Source:155)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:10)
	... 5 more
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@78f3d86, Dispatchers.Default]
```
